export const BUILTIN_LISTS: BuiltinList[] = [
  {
    id: 'cefr-a1', label: 'A1 基础', level: 'A1',
    words: [
      { text: 'hello', meaning: '你好', example: 'Hello, nice to meet you today.' },
      { text: 'water', meaning: '水', example: 'Can I have a glass of water?' },
      { text: 'friend', meaning: '朋友', example: 'She is my best friend at school.' },
      { text: 'house', meaning: '房子', example: 'We live in a small house near the park.' },
      { text: 'apple', meaning: '苹果', example: 'I eat an apple every morning.' },
      { text: 'family', meaning: '家庭', example: 'My family has four people in it.' },
      { text: 'morning', meaning: '早上', example: 'I wake up early every morning.' },
      { text: 'school', meaning: '学校', example: 'The children go to school by bus.' },
      { text: 'happy', meaning: '快乐', example: 'She looks very happy today.' },
      { text: 'food', meaning: '食物', example: 'The food at this restaurant is great.' },
      { text: 'book', meaning: '书', example: 'I read a book before I go to sleep.' },
      { text: 'money', meaning: '钱', example: 'He does not have much money.' },
      { text: 'time', meaning: '时间', example: 'What time does the movie start?' },
      { text: 'work', meaning: '工作', example: 'My father goes to work every day.' },
      { text: 'woman', meaning: '女人', example: 'The woman is walking her dog outside.' },
      { text: 'child', meaning: '孩子', example: 'The child is playing in the garden.' },
      { text: 'night', meaning: '晚上', example: 'The stars are bright at night.' },
      { text: 'door', meaning: '门', example: 'Please close the door behind you.' },
      { text: 'city', meaning: '城市', example: 'Beijing is a very big city in China.' },
      { text: 'country', meaning: '国家', example: 'Japan is a beautiful country to visit.' },
      { text: 'car', meaning: '汽车', example: 'He drives his car to work every day.' },
      { text: 'music', meaning: '音乐', example: 'She likes to listen to music at home.' },
      { text: 'garden', meaning: '花园', example: 'We plant flowers in our garden each spring.' },
      { text: 'letter', meaning: '信', example: 'I wrote a letter to my grandmother last week.' },
      { text: 'answer', meaning: '回答', example: 'Please answer the question in full sentences.' },
      { text: 'store', meaning: '商店', example: 'We buy our food at the store nearby.' },
      { text: 'tired', meaning: '累', example: 'I feel very tired after a long day.' },
      { text: 'young', meaning: '年轻', example: 'The young man works at a bank downtown.' },
      { text: 'black', meaning: '黑色', example: 'She is wearing a black jacket today.' },
      { text: 'rain', meaning: '下雨', example: 'It will rain all day tomorrow afternoon.' },
    ],
  },
  {
    id: 'cefr-a2', label: 'A2 初级', level: 'A2',
    words: [
      { text: 'advice', meaning: '建议', example: 'Can you give me some advice on this?' },
      { text: 'agree', meaning: '同意', example: 'I agree with everything you just said.' },
      { text: 'afraid', meaning: '害怕', example: 'She is afraid of spiders in the house.' },
      { text: 'already', meaning: '已经', example: 'I have already finished my homework today.' },
      { text: 'arrive', meaning: '到达', example: 'We arrived at the airport two hours early.' },
      { text: 'borrow', meaning: '借入', example: 'Can I borrow your pen for a minute?' },
      { text: 'branch', meaning: '树枝', example: 'The bird sat on a branch of the tree.' },
      { text: 'careful', meaning: '小心', example: 'Be careful when you cross the busy street.' },
      { text: 'choose', meaning: '选择', example: 'Please choose the color you like best.' },
      { text: 'correct', meaning: '正确的', example: 'Your answer is correct and well explained.' },
      { text: 'dangerous', meaning: '危险', example: 'Swimming in this river is very dangerous.' },
      { text: 'delicious', meaning: '美味', example: 'This cake tastes absolutely delicious today.' },
      { text: 'disappear', meaning: '消失', example: 'The rabbit seemed to disappear into thin air.' },
      { text: 'encourage', meaning: '鼓励', example: 'My teacher always encourages me to try harder.' },
      { text: 'exchange', meaning: '交换', example: 'We can exchange gifts at the party tonight.' },
      { text: 'expensive', meaning: '昂贵', example: 'This phone is too expensive for me to buy.' },
      { text: 'forget', meaning: '忘记', example: 'I always forget to bring my umbrella outside.' },
      { text: 'improve', meaning: '提高', example: 'I want to improve my English speaking skills.' },
      { text: 'include', meaning: '包括', example: 'The price does not include tax or service.' },
      { text: 'innocent', meaning: '无辜', example: 'The innocent child did not know about the lie.' },
      { text: 'journey', meaning: '旅程', example: 'The long journey to our destination takes five hours.' },
      { text: 'knowledge', meaning: '知识', example: 'Reading gives us knowledge about the world.' },
      { text: 'language', meaning: '语言', example: 'Learning a new language takes time and effort.' },
      { text: 'natural', meaning: '自然', example: 'The park has many beautiful natural landscapes.' },
      { text: 'patient', meaning: '耐心', example: 'You must be patient when waiting for the bus.' },
      { text: 'popular', meaning: '受欢迎', example: 'Football is a very popular sport in Europe.' },
      { text: 'remember', meaning: '记得', example: 'I remember meeting you at the party last year.' },
      { text: 'surprise', meaning: '惊喜', example: 'The party was a wonderful surprise for Mom.' },
      { text: 'usual', meaning: '通常', example: 'She takes the usual bus to school every morning.' },
      { text: 'weather', meaning: '天气', example: 'The weather is very warm and sunny this week.' },
    ],
  },
  {
    id: 'cefr-b1', label: 'B1 中级', level: 'B1',
    words: [
      { text: 'achieve', meaning: '实现', example: 'She worked hard to achieve her career goals.' },
      { text: 'advantage', meaning: '优势', example: 'Being tall is an advantage in basketball games.' },
      { text: 'anxious', meaning: '焦虑', example: 'He felt anxious before the job interview today.' },
      { text: 'compete', meaning: '竞争', example: 'Ten runners will compete in the final race tomorrow.' },
      { text: 'complain', meaning: '抱怨', example: 'Please do not complain about the small problems.' },
      { text: 'confidence', meaning: '信心', example: 'She spoke with great confidence in front of everyone.' },
      { text: 'convenient', meaning: '方便', example: 'The store is in a very convenient location downtown.' },
      { text: 'describe', meaning: '描述', example: 'Can you describe what the suspect looked like?' },
      { text: 'develop', meaning: '发展', example: 'We need to develop new ideas for the project.' },
      { text: 'economy', meaning: '经济', example: 'The economy has improved quite a lot this year.' },
      { text: 'effective', meaning: '有效', example: 'This method is very effective for learning new words.' },
      { text: 'emergency', meaning: '紧急情况', example: 'Call 911 immediately if there is an emergency.' },
      { text: 'entire', meaning: '全部', example: 'She read the entire book in just one evening.' },
      { text: 'establish', meaning: '建立', example: 'The school was established over a hundred years ago.' },
      { text: 'gradually', meaning: '逐渐', example: 'The weather gradually got warmer through the spring.' },
      { text: 'hesitate', meaning: '犹豫', example: 'Do not hesitate to ask me if you need help.' },
      { text: 'ignore', meaning: '忽视', example: 'You should not ignore the warning signs at all.' },
      { text: 'influence', meaning: '影响', example: 'Parents have a big influence on their children.' },
      { text: 'magnificent', meaning: '壮丽', example: 'The view from the mountain top was absolutely magnificent.' },
      { text: 'obvious', meaning: '明显', example: 'It is obvious that she has been working very hard.' },
      { text: 'opportunity', meaning: '机会', example: 'Studying abroad is a great opportunity for students.' },
      { text: 'ordinary', meaning: '普通', example: 'It was just an ordinary day at the office today.' },
      { text: 'persuade', meaning: '说服', example: 'I tried to persuade him to come to the party.' },
      { text: 'phenomenon', meaning: '现象', example: 'The Northern Lights are a beautiful natural phenomenon.' },
      { text: 'principle', meaning: '原则', example: 'She always follows her principles in life and work.' },
      { text: 'reliable', meaning: '可靠', example: 'He is a very reliable person you can count on.' },
      { text: 'sacrifice', meaning: '牺牲', example: 'Parents often sacrifice their own needs for children.' },
      { text: 'sufficient', meaning: '足够', example: 'We have sufficient food and water for the journey.' },
      { text: 'temporary', meaning: '暂时', example: 'This is only a temporary solution to our problem.' },
      { text: 'valuable', meaning: '有价值', example: 'The old painting is extremely valuable and rare.' },
    ],
  },
  {
    id: 'cefr-b2', label: 'B2 中高级', level: 'B2',
    words: [
      { text: 'ambiguous', meaning: '模棱两可', example: 'His ambiguous reply left everyone feeling confused.' },
      { text: 'anticipate', meaning: '预期', example: 'We did not anticipate so many people attending the event.' },
      { text: 'apparent', meaning: '明显', example: 'It was apparent that the plan would not work out.' },
      { text: 'bias', meaning: '偏见', example: 'The report shows a clear bias against certain groups.' },
      { text: 'cease', meaning: '停止', example: 'The company was forced to cease all operations immediately.' },
      { text: 'coherent', meaning: '连贯', example: 'She presented a coherent argument in favor of the idea.' },
      { text: 'comprehensive', meaning: '全面', example: 'The report provides a comprehensive overview of the data.' },
      { text: 'compromise', meaning: '妥协', example: 'Both sides must compromise to reach an agreement.' },
      { text: 'consequently', meaning: '因此', example: 'He missed the deadline; consequently, he lost the contract.' },
      { text: 'contradict', meaning: '矛盾', example: 'The evidence seems to contradict his statement about it.' },
      { text: 'controversial', meaning: '有争议', example: 'The new law has become very controversial among citizens.' },
      { text: 'deceive', meaning: '欺骗', example: 'He tried to deceive the police with a false alibi.' },
      { text: 'diminish', meaning: '减少', example: 'Nothing can diminish the importance of this discovery.' },
      { text: 'elaborate', meaning: '详细', example: 'Could you elaborate on your proposal for the project?' },
      { text: 'ethical', meaning: '道德', example: 'It raises serious ethical concerns about the treatment.' },
      { text: 'exaggerate', meaning: '夸大', example: 'The media tends to exaggerate the severity of the problem.' },
      { text: 'fluctuate', meaning: '波动', example: 'Stock prices tend to fluctuate throughout the trading day.' },
      { text: 'genuine', meaning: '真实', example: 'Her concern for the environment is absolutely genuine.' },
      { text: 'hypothesis', meaning: '假设', example: 'The scientist tested her hypothesis through careful experiments.' },
      { text: 'implement', meaning: '实施', example: 'The school decided to implement the new teaching method.' },
      { text: 'inevitable', meaning: '不可避免', example: 'Change is inevitable in any growing organization today.' },
      { text: 'legitimate', meaning: '合法', example: 'The company has a legitimate claim to the intellectual property.' },
      { text: 'negligible', meaning: '微不足道', example: 'The cost difference between the two options is negligible.' },
      { text: 'paradox', meaning: '悖论', example: 'It is a paradox that more choice causes less satisfaction.' },
      { text: 'pragmatic', meaning: '务实', example: 'We need a pragmatic approach to solve this complex problem.' },
      { text: 'prevalent', meaning: '普遍', example: 'Misinformation is prevalent on social media platforms today.' },
      { text: 'profound', meaning: '深刻', example: 'The book had a profound impact on my worldview and values.' },
      { text: 'rigid', meaning: '僵硬', example: 'The company has a very rigid policy on employee attendance.' },
      { text: 'subtle', meaning: '微妙', example: 'There is a subtle difference between the two similar words.' },
      { text: 'vulnerable', meaning: '脆弱', example: 'Children are especially vulnerable to the effects of pollution.' },
    ],
  },
  {
    id: 'cefr-c1', label: 'C1 高级', level: 'C1',
    words: [
      { text: 'acquiesce', meaning: '默许', example: 'She decided to acquiesce to the demands of her manager.' },
      { text: 'alleviate', meaning: '减轻', example: 'The new policy aims to alleviate poverty in rural areas.' },
      { text: 'ambivalent', meaning: '矛盾心情', example: 'He felt ambivalent about accepting the overseas position.' },
      { text: 'austere', meaning: '简朴', example: 'The monks lived a simple and austere life in the mountains.' },
      { text: 'capitulate', meaning: '屈服', example: 'After months of resistance, the company finally capitulated.' },
      { text: 'candid', meaning: '坦率', example: 'I appreciate your candid feedback on my presentation today.' },
      { text: 'clandestine', meaning: '秘密', example: 'The agents conducted a clandestine operation across the border.' },
      { text: 'circumvent', meaning: '规避', example: 'They found a way to circumvent the regulations entirely with loopholes.' },
      { text: 'cynical', meaning: '愤世嫉俗', example: 'He has grown increasingly cynical about the political process.' },
      { text: 'deteriorate', meaning: '恶化', example: 'His health continued to deteriorate over the past few months.' },
      { text: 'diligent', meaning: '勤奋', example: 'The diligent student reviewed her notes every single evening.' },
      { text: 'discrepancy', meaning: '差异', example: 'There is a discrepancy between the two sets of financial data.' },
      { text: 'empirical', meaning: '经验主义', example: 'The theory must be supported by empirical evidence from studies.' },
      { text: 'endeavor', meaning: '努力', example: 'We will endeavor to finish the project before the deadline.' },
      { text: 'enumerate', meaning: '列举', example: 'She was asked to enumerate all the reasons for her decision.' },
      { text: 'formidable', meaning: '令人生畏', example: 'The team faces a formidable opponent in the championship match.' },
      { text: 'hinder', meaning: '阻碍', example: 'Poor infrastructure continues to hinder economic growth in the region.' },
      { text: 'impede', meaning: '妨碍', example: 'Red tape can significantly impede progress on important reforms.' },
      { text: 'meticulous', meaning: '一丝不苟', example: 'The meticulous artist spent hours on every tiny detail.' },
      { text: 'mundane', meaning: '平凡', example: 'She found her mundane office routine quite unfulfilling over time.' },
      { text: 'nostalgia', meaning: '怀旧', example: 'Looking at old photos filled her with a deep sense of nostalgia.' },
      { text: 'obscure', meaning: '晦涩', example: 'The meaning of the poem remains somewhat obscure to most readers.' },
      { text: 'optimal', meaning: '最佳', example: 'The optimal temperature for storing wine is about fifteen degrees.' },
      { text: 'peripheral', meaning: '外围', example: 'These are only peripheral issues and not the main concern.' },
      { text: 'resilient', meaning: '有韧性', example: 'The community proved to be remarkably resilient after the disaster.' },
      { text: 'scrutiny', meaning: '审查', example: 'The proposal came under intense scrutiny from the review committee.' },
      { text: 'spontaneous', meaning: '自发', example: 'The spontaneous applause from the audience was truly wonderful.' },
      { text: 'superficial', meaning: '表面', example: 'His understanding of the issue is rather superficial at best.' },
      { text: 'tangible', meaning: '有形', example: 'We need to see tangible results before investing more money.' },
      { text: 'tenacious', meaning: '顽强', example: 'The tenacious reporter uncovered the truth behind the scandal.' },
    ],
  },
  {
    id: 'cefr-c2', label: 'C2 精通', level: 'C2',
    words: [
      { text: 'aberration', meaning: '偏差', example: 'The warm weather in December was a complete aberration from normal.' },
      { text: 'ameliorate', meaning: '改善', example: 'The new regulations aim to ameliorate working conditions for employees.' },
      { text: 'anomaly', meaning: '异常', example: 'The test results showed a significant anomaly in the data set.' },
      { text: 'benevolent', meaning: '仁慈', example: 'The benevolent donor funded scholarships for hundreds of students.' },
      { text: 'brevity', meaning: '简洁', example: 'The brevity of his speech made it all the more powerful indeed.' },
      { text: 'circumlocution', meaning: '迂回', example: 'His circumlocution made it hard to understand his actual point.' },
      { text: 'commensurate', meaning: '相称', example: 'Her salary is commensurate with her level of experience and skill.' },
      { text: 'conciliatory', meaning: '安抚', example: 'She adopted a conciliatory tone to defuse the tense meeting situation.' },
      { text: 'confluence', meaning: '汇合', example: 'The confluence of cultural influences makes the cuisine truly unique.' },
      { text: 'conundrum', meaning: '难题', example: 'The budget deficit poses a serious conundrum for the new government.' },
      { text: 'corroborate', meaning: '佐证', example: 'Additional testimony helped corroborate the key findings of the investigation.' },
      { text: 'dearth', meaning: '缺乏', example: 'There is a dearth of qualified candidates for this specialized position.' },
      { text: 'debilitate', meaning: '使衰弱', example: 'The prolonged illness continued to debilitate him throughout the year.' },
      { text: 'delineate', meaning: '描绘', example: 'The report clearly delineates the responsibilities of each department.' },
      { text: 'disparate', meaning: '截然不同', example: 'The study compared disparate cultures across three different continents.' },
      { text: 'duplicity', meaning: '欺诈', example: 'Her duplicity was finally exposed by the investigative journalism team.' },
      { text: 'eloquent', meaning: '雄辩', example: 'The eloquent speaker moved the entire audience to tears and applause.' },
      { text: 'emollient', meaning: '缓和', example: 'His emollient words helped calm the angry crowd outside the building.' },
      { text: 'ephemeral', meaning: '短暂', example: 'Fame in the modern world is often painfully ephemeral and fragile.' },
      { text: 'equivocal', meaning: '模棱两可', example: 'The politician gave an equivocal response that satisfied no one at all.' },
      { text: 'erudite', meaning: '博学', example: 'The erudite professor quoted from dozens of ancient classical texts.' },
      { text: 'exacerbate', meaning: '加剧', example: 'The drought will exacerbate the existing water shortage problem for farmers.' },
      { text: 'fallacious', meaning: '谬误', example: 'The argument is based on completely fallacious logic and false assumptions.' },
      { text: 'hapless', meaning: '不幸', example: 'The hapless traveler lost both his luggage and his passport on the trip.' },
      { text: 'impervious', meaning: '不受影响', example: 'She seemed impervious to the criticism from her detractors and opponents.' },
      { text: 'inchoate', meaning: '初期', example: 'The plan was still inchoate and needed much more detailed development.' },
      { text: 'insipid', meaning: '乏味', example: 'The insipid dialogue made the film nearly impossible to sit through.' },
      { text: 'juxtapose', meaning: '并列', example: 'The exhibit juxtaposes ancient artifacts with modern digital artwork pieces.' },
      { text: 'perfunctory', meaning: '敷衍', example: 'He gave only a perfunctory glance at the contract before signing it.' },
      { text: 'surreptitious', meaning: '偷偷摸摸', example: 'She took a surreptitious photograph of the confidential document at night.' },
    ],
  },
];
