/**
 * Ogden's Basic English 850 core vocabulary.
 * Each entry includes a concise Chinese meaning and a simple example sentence
 * using only Basic English words.
 */
export const BASIC_ENGLISH_850: Array<{ text: string; meaning: string; example: string }> = [
  // ── Operations (15) ──
  { text: 'come', meaning: '来', example: 'Please come to my home.' },
  { text: 'do', meaning: '做', example: 'What do you do every day?' },
  { text: 'get', meaning: '得到', example: 'I want to get a good price.' },
  { text: 'give', meaning: '给', example: 'Give me the book, please.' },
  { text: 'go', meaning: '去', example: 'We go to the park on Sunday.' },
  { text: 'keep', meaning: '保持', example: 'Keep the room clean.' },
  { text: 'know', meaning: '知道', example: 'I know the right answer.' },
  { text: 'let', meaning: '让', example: 'Let me help you with that.' },
  { text: 'make', meaning: '制作', example: 'She makes good food every day.' },
  { text: 'put', meaning: '放', example: 'Put the cup on the table.' },
  { text: 'say', meaning: '说', example: 'What did you say to him?' },
  { text: 'see', meaning: '看', example: 'I can see the mountain from here.' },
  { text: 'send', meaning: '发送', example: 'Please send me the letter.' },
  { text: 'take', meaning: '拿', example: 'Take this pen with you.' },
  { text: 'think', meaning: '想', example: 'I think this is the right way.' },

  // ── Things (100) ──
  { text: 'account', meaning: '账户', example: 'I have an account at the bank.' },
  { text: 'act', meaning: '行为', example: 'That was a kind act.' },
  { text: 'action', meaning: '行动', example: 'Action is better than words.' },
  { text: 'adjustment', meaning: '调整', example: 'This adjustment will help.' },
  { text: 'advertisement', meaning: '广告', example: 'I saw an advertisement on the wall.' },
  { text: 'agreement', meaning: '协议', example: 'We have an agreement on this.' },
  { text: 'amount', meaning: '数量', example: 'A large amount of water fell.' },
  { text: 'angle', meaning: '角度', example: 'Look at this from every angle.' },
  { text: 'animal', meaning: '动物', example: 'The dog is a friendly animal.' },
  { text: 'answer', meaning: '回答', example: 'Give me the right answer.' },
  { text: 'apparatus', meaning: '设备', example: 'The apparatus works well.' },
  { text: 'apple', meaning: '苹果', example: 'I eat an apple every day.' },
  { text: 'application', meaning: '申请', example: 'Send in your application now.' },
  { text: 'arm', meaning: '手臂', example: 'He broke his arm in the fall.' },
  { text: 'army', meaning: '军队', example: 'The army protects the country.' },
  { text: 'art', meaning: '艺术', example: 'She studies art at school.' },
  { text: 'attack', meaning: '攻击', example: 'The attack came at night.' },
  { text: 'attention', meaning: '注意', example: 'Pay attention to the teacher.' },
  { text: 'attempt', meaning: '尝试', example: 'Make an attempt to solve it.' },
  { text: 'authority', meaning: '权威', example: 'He has authority over the group.' },
  { text: 'baby', meaning: '婴儿', example: 'The baby is sleeping now.' },
  { text: 'back', meaning: '背', example: 'Put the bag on your back.' },
  { text: 'bag', meaning: '包', example: 'Carry this bag for me.' },
  { text: 'balance', meaning: '平衡', example: 'Keep your balance on the ice.' },
  { text: 'base', meaning: '基础', example: 'The house has a strong base.' },
  { text: 'behavior', meaning: '行为', example: 'Good behavior is important.' },
  { text: 'belief', meaning: '信念', example: 'That is my belief on this matter.' },
  { text: 'birth', meaning: '出生', example: 'What is the date of your birth?' },
  { text: 'bit', meaning: '一点儿', example: 'Wait a bit and try again.' },
  { text: 'blood', meaning: '血', example: 'Blood is red in color.' },
  { text: 'blow', meaning: '吹', example: 'The wind blows from the north.' },
  { text: 'board', meaning: '板', example: 'Write on the board, please.' },
  { text: 'boat', meaning: '船', example: 'We go across the water by boat.' },
  { text: 'body', meaning: '身体', example: 'Take good care of your body.' },
  { text: 'bomb', meaning: '炸弹', example: 'The bomb was found by the army.' },
  { text: 'bone', meaning: '骨头', example: 'The dog likes to eat the bone.' },
  { text: 'book', meaning: '书', example: 'I am reading a good book.' },
  { text: 'border', meaning: '边界', example: 'We reached the border at noon.' },
  { text: 'bottom', meaning: '底部', example: 'The key is at the bottom of the bag.' },
  { text: 'box', meaning: '盒子', example: 'Put the food in the box.' },
  { text: 'brain', meaning: '大脑', example: 'The brain controls the body.' },
  { text: 'branch', meaning: '树枝', example: 'A bird sat on the branch.' },
  { text: 'breath', meaning: '呼吸', example: 'Take a deep breath now.' },
  { text: 'brother', meaning: '兄弟', example: 'My brother is older than me.' },
  { text: 'building', meaning: '建筑', example: 'That is a very tall building.' },
  { text: 'burn', meaning: '燃烧', example: 'The fire burns very hot.' },
  { text: 'burst', meaning: '爆炸', example: 'The balloon may burst if you blow more.' },
  { text: 'button', meaning: '按钮', example: 'Press the button to start.' },
  { text: 'camera', meaning: '相机', example: 'Take a photo with the camera.' },
  { text: 'camp', meaning: '营地', example: 'We set up camp near the river.' },
  { text: 'cap', meaning: '帽子', example: 'Wear your cap in the sun.' },
  { text: 'card', meaning: '卡片', example: 'Send her a birthday card.' },
  { text: 'cart', meaning: '手推车', example: 'Put the bags in the cart.' },
  { text: 'case', meaning: '箱子', example: 'The case is full of clothes.' },
  { text: 'cat', meaning: '猫', example: 'The cat is on the chair.' },
  { text: 'center', meaning: '中心', example: 'The store is in the center of town.' },
  { text: 'chain', meaning: '链子', example: 'The chain is made of metal.' },
  { text: 'chair', meaning: '椅子', example: 'Sit down on this chair.' },
  { text: 'chance', meaning: '机会', example: 'Give me a chance to try.' },
  { text: 'check', meaning: '检查', example: 'Check your work before you finish.' },
  { text: 'church', meaning: '教堂', example: 'We go to church on Sunday.' },
  { text: 'circle', meaning: '圆', example: 'Draw a circle on the paper.' },
  { text: 'citizen', meaning: '公民', example: 'Every citizen has a right to vote.' },
  { text: 'cloud', meaning: '云', example: 'The cloud is dark and big.' },
  { text: 'coat', meaning: '外套', example: 'Wear your coat, it is cold.' },
  { text: 'color', meaning: '颜色', example: 'What color do you like best?' },
  { text: 'column', meaning: '柱', example: 'The column holds up the roof.' },
  { text: 'comb', meaning: '梳子', example: 'Use a comb for your hair.' },
  { text: 'comfort', meaning: '舒适', example: 'This chair gives me great comfort.' },
  { text: 'command', meaning: '命令', example: 'Give the command to start.' },
  { text: 'company', meaning: '公司', example: 'He works for a big company.' },
  { text: 'control', meaning: '控制', example: 'Who is in control here?' },
  { text: 'cotton', meaning: '棉花', example: 'This shirt is made of cotton.' },
  { text: 'cough', meaning: '咳嗽', example: 'He has a bad cough today.' },
  { text: 'country', meaning: '国家', example: 'This is a beautiful country.' },
  { text: 'cover', meaning: '覆盖', example: 'Cover the pot with a lid.' },
  { text: 'crack', meaning: '裂缝', example: 'There is a crack in the wall.' },
  { text: 'credit', meaning: '信用', example: 'He has good credit at the bank.' },
  { text: 'crowd', meaning: '人群', example: 'A large crowd came to the show.' },
  { text: 'cup', meaning: '杯子', example: 'Pour some tea in the cup.' },
  { text: 'current', meaning: '水流', example: 'The current in the river is strong.' },
  { text: 'curve', meaning: '曲线', example: 'The road has a big curve here.' },
  { text: 'damage', meaning: '损害', example: 'The storm caused much damage.' },
  { text: 'danger', meaning: '危险', example: 'There is danger in the old house.' },
  { text: 'daughter', meaning: '女儿', example: 'Their daughter is very kind.' },
  { text: 'day', meaning: '天', example: 'Today is a good day to start.' },
  { text: 'death', meaning: '死亡', example: 'His death was a great loss.' },
  { text: 'design', meaning: '设计', example: 'She made a beautiful design.' },
  { text: 'desire', meaning: '欲望', example: 'My desire is to help others.' },
  { text: 'destruction', meaning: '破坏', example: 'The destruction of the building was total.' },
  { text: 'detail', meaning: '细节', example: 'Tell me every detail of the plan.' },
  { text: 'development', meaning: '发展', example: 'The development of this city is fast.' },
  { text: 'digestion', meaning: '消化', example: 'Good food helps your digestion.' },
  { text: 'able', meaning: '能够', example: 'I am able to swim well.' },
  { text: 'abnormal', meaning: '异常', example: 'That is abnormal behavior.' },
  { text: 'abroad', meaning: '国外', example: 'She lives abroad now.' },
  { text: 'absent', meaning: '缺席', example: 'He was absent from class.' },
  { text: 'absolute', meaning: '绝对', example: 'That is the absolute truth.' },
  { text: 'accept', meaning: '接受', example: 'Please accept my gift.' },
  { text: 'accident', meaning: '事故', example: 'The accident happened at noon.' },

  // ── General Words (300) ──
  { text: 'actual', meaning: '实际', example: 'What is the actual number?' },
  { text: 'add', meaning: '加', example: 'Add two more to the list.' },
  { text: 'adult', meaning: '成人', example: 'Every adult must vote.' },
  { text: 'afraid', meaning: '害怕', example: 'I am afraid of the dark.' },
  { text: 'agree', meaning: '同意', example: 'I agree with your idea.' },
  { text: 'ahead', meaning: '前面', example: 'Go ahead and start now.' },
  { text: 'alive', meaning: '活着', example: 'The fish is still alive.' },
  { text: 'allow', meaning: '允许', example: 'Do not allow him to go.' },
  { text: 'alone', meaning: '独自', example: 'She lives alone in the city.' },
  { text: 'among', meaning: '在…之中', example: 'He is the best among them.' },
  { text: 'apart', meaning: '分开', example: 'Put the two things apart.' },
  { text: 'apologize', meaning: '道歉', example: 'I must apologize for being late.' },
  { text: 'appear', meaning: '出现', example: 'The sun appears at dawn.' },
  { text: 'approve', meaning: '赞成', example: 'The group will approve the plan.' },
  { text: 'around', meaning: '周围', example: 'Look around and tell me what you see.' },
  { text: 'arrive', meaning: '到达', example: 'We arrive at the station at nine.' },
  { text: 'aside', meaning: '旁边', example: 'Put it aside for later.' },
  { text: 'associate', meaning: '联系', example: 'I associate music with joy.' },
  { text: 'attach', meaning: '附上', example: 'Attach the file to the letter.' },
  { text: 'available', meaning: '可用', example: 'Is this seat available?' },
  { text: 'average', meaning: '平均', example: 'The average age is thirty.' },
  { text: 'avoid', meaning: '避免', example: 'Avoid going out in the rain.' },
  { text: 'awake', meaning: '醒着', example: 'I was awake all night long.' },
  { text: 'aware', meaning: '意识到', example: 'Are you aware of the danger?' },
  { text: 'bad', meaning: '坏', example: 'That is a bad idea for sure.' },
  { text: 'basic', meaning: '基本', example: 'These are the basic rules.' },
  { text: 'beautiful', meaning: '美丽', example: 'That is a beautiful picture.' },
  { text: 'bed', meaning: '床', example: 'Go to bed now, it is late.' },
  { text: 'bend', meaning: '弯曲', example: 'Bend your knees when you lift.' },
  { text: 'best', meaning: '最好', example: 'This is the best day of my life.' },
  { text: 'bitter', meaning: '苦', example: 'This medicine has a bitter taste.' },
  { text: 'black', meaning: '黑色', example: 'The cat has black fur.' },
  { text: 'blue', meaning: '蓝色', example: 'The sky is blue today.' },
  { text: 'bold', meaning: '大胆', example: 'That was a very bold action.' },
  { text: 'born', meaning: '出生', example: 'I was born in this town.' },
  { text: 'both', meaning: '两者都', example: 'Both of them are good.' },
  { text: 'bright', meaning: '明亮', example: 'The light is very bright.' },
  { text: 'broad', meaning: '宽', example: 'The road is very broad here.' },
  { text: 'brown', meaning: '棕色', example: 'The table is dark brown.' },
  { text: 'busy', meaning: '忙碌', example: 'I am very busy today.' },
  { text: 'calm', meaning: '平静', example: 'Keep calm and carry on.' },
  { text: 'capable', meaning: '有能力', example: 'She is capable of doing the work.' },
  { text: 'care', meaning: '关心', example: 'Take care of yourself.' },
  { text: 'careful', meaning: '小心', example: 'Be careful when you cross the road.' },
  { text: 'certain', meaning: '确定', example: 'I am certain he will come.' },
  { text: 'cheap', meaning: '便宜', example: 'This book is very cheap.' },
  { text: 'clear', meaning: '清楚', example: 'Make your answer clear and simple.' },
  { text: 'clever', meaning: '聪明', example: 'That was a clever idea.' },
  { text: 'close', meaning: '近', example: 'The store is close to my home.' },
  { text: 'cold', meaning: '冷', example: 'It is very cold outside today.' },
  { text: 'comfortable', meaning: '舒适', example: 'This chair is very comfortable.' },
  { text: 'common', meaning: '常见', example: 'That is a common problem.' },
  { text: 'complete', meaning: '完整', example: 'Is the report complete now?' },
  { text: 'concerned', meaning: '关心', example: 'I am concerned about your health.' },
  { text: 'content', meaning: '满足', example: 'Are you content with this result?' },
  { text: 'continue', meaning: '继续', example: 'Please continue with your story.' },
  { text: 'correct', meaning: '正确', example: 'That is the correct answer.' },
  { text: 'cost', meaning: '花费', example: 'What does this cost in total?' },
  { text: 'cross', meaning: '穿过', example: 'Cross the road at the light.' },
  { text: 'crowded', meaning: '拥挤', example: 'The bus is very crowded today.' },
  { text: 'cruel', meaning: '残忍', example: 'It is cruel to hurt animals.' },
  { text: 'daily', meaning: '每天', example: 'I take a daily walk in the park.' },
  { text: 'deep', meaning: '深', example: 'The river is very deep here.' },
  { text: 'definite', meaning: '明确', example: 'Give me a definite answer.' },
  { text: 'delicate', meaning: '精致', example: 'This is a very delicate piece of art.' },
  { text: 'delightful', meaning: '令人愉快', example: 'We had a delightful time.' },
  { text: 'different', meaning: '不同', example: 'The two books are very different.' },
  { text: 'difficult', meaning: '困难', example: 'This question is very difficult.' },
  { text: 'direct', meaning: '直接', example: 'Take the direct road to the city.' },
  { text: 'dirty', meaning: '脏', example: 'Your hands are very dirty.' },
  { text: 'dry', meaning: '干', example: 'The cloth is now dry and clean.' },
  { text: 'early', meaning: '早', example: 'She always gets up early.' },
  { text: 'east', meaning: '东方', example: 'The sun rises in the east.' },
  { text: 'easy', meaning: '容易', example: 'This test is very easy for me.' },
  { text: 'effect', meaning: '效果', example: 'What is the effect of this medicine?' },
  { text: 'efficient', meaning: '高效', example: 'She is an efficient worker.' },
  { text: 'else', meaning: '其他', example: 'What else do you need now?' },
  { text: 'empty', meaning: '空', example: 'The room is empty and clean.' },
  { text: 'end', meaning: '结束', example: 'At the end of the road turn left.' },
  { text: 'equal', meaning: '平等', example: 'All people are equal in this land.' },
  { text: 'especial', meaning: '特别', example: 'This is of especial importance.' },
  { text: 'even', meaning: '甚至', example: 'Even a child can do this.' },
  { text: 'eventual', meaning: '最终', example: 'His eventual success was great.' },
  { text: 'evil', meaning: '邪恶', example: 'That was an evil plan.' },
  { text: 'exact', meaning: '精确', example: 'Tell me the exact time.' },
  { text: 'excellent', meaning: '优秀', example: 'That is an excellent idea.' },
  { text: 'except', meaning: '除了', example: 'Everyone came except Tom.' },
  { text: 'excited', meaning: '兴奋', example: 'I am excited about the trip.' },
  { text: 'exciting', meaning: '令人兴奋', example: 'That was an exciting game.' },
  { text: 'existing', meaning: '现有的', example: 'We must use the existing plan.' },
  { text: 'extra', meaning: '额外', example: 'Do you have any extra time?' },
  { text: 'extreme', meaning: '极端', example: 'That is an extreme case.' },
  { text: 'fact', meaning: '事实', example: 'That is a known fact to everyone.' },
  { text: 'fair', meaning: '公平', example: 'We must be fair to all people.' },
  { text: 'false', meaning: '错误', example: 'That statement is false and wrong.' },
  { text: 'familiar', meaning: '熟悉', example: 'This place looks familiar to me.' },
  { text: 'far', meaning: '远', example: 'The town is far from here.' },
  { text: 'fast', meaning: '快', example: 'He can run very fast indeed.' },
  { text: 'fat', meaning: '胖', example: 'The cat is getting too fat.' },
  { text: 'few', meaning: '少', example: 'Only a few people came today.' },
  { text: 'final', meaning: '最后', example: 'This is the final decision.' },
  { text: 'fine', meaning: '好', example: 'I am feeling fine today.' },
  { text: 'firm', meaning: '坚定', example: 'Be firm in your decisions.' },
  { text: 'flat', meaning: '平', example: 'The road is flat and smooth.' },
  { text: 'foreign', meaning: '外国', example: 'He studies a foreign language.' },
  { text: 'former', meaning: '前者', example: 'The former plan was better.' },
  { text: 'free', meaning: '自由', example: 'You are free to go now.' },
  { text: 'frequent', meaning: '频繁', example: 'He is a frequent visitor here.' },
  { text: 'fresh', meaning: '新鲜', example: 'We have fresh bread every morning.' },
  { text: 'front', meaning: '前面', example: 'Stand at the front of the line.' },
  { text: 'full', meaning: '满', example: 'The glass is full of water.' },
  { text: 'general', meaning: '一般', example: 'This is the general rule for all.' },
  { text: 'gentle', meaning: '温柔', example: 'Be gentle with the small child.' },
  { text: 'genuine', meaning: '真正的', example: 'This is a genuine piece of art.' },
  { text: 'glad', meaning: '高兴', example: 'I am glad to see you again.' },
  { text: 'gold', meaning: '金子', example: 'The ring is made of gold.' },
  { text: 'good', meaning: '好', example: 'That is a very good idea.' },
  { text: 'gray', meaning: '灰色', example: 'The cat has gray fur.' },
  { text: 'great', meaning: '伟大', example: 'That was a great success.' },
  { text: 'green', meaning: '绿色', example: 'The grass is green in spring.' },
  { text: 'guilty', meaning: '有罪', example: 'He was found guilty at court.' },
  { text: 'happy', meaning: '快乐', example: 'I am very happy today.' },
  { text: 'hard', meaning: '硬', example: 'This work is very hard to do.' },
  { text: 'heavy', meaning: '重', example: 'The box is too heavy for me.' },
  { text: 'high', meaning: '高', example: 'The mountain is very high.' },
  { text: 'hollow', meaning: '空心', example: 'The tree is hollow inside.' },
  { text: 'honest', meaning: '诚实', example: 'He is an honest person.' },
  { text: 'hot', meaning: '热', example: 'The water is very hot today.' },
  { text: 'huge', meaning: '巨大', example: 'That is a huge building.' },
  { text: 'ill', meaning: '生病', example: 'She has been ill for three days.' },
  { text: 'important', meaning: '重要', example: 'This is an important meeting.' },
  { text: 'impossible', meaning: '不可能', example: 'Nothing is impossible if you try.' },
  { text: 'indeed', meaning: '确实', example: 'That is indeed very kind of you.' },
  { text: 'independent', meaning: '独立', example: 'She is a very independent person.' },
  { text: 'industrial', meaning: '工业', example: 'This is an industrial area of town.' },
  { text: 'intelligent', meaning: '聪明', example: 'She is very intelligent and kind.' },
  { text: 'interested', meaning: '感兴趣', example: 'I am interested in this subject.' },
  { text: 'interesting', meaning: '有趣', example: 'That is a very interesting book.' },
  { text: 'international', meaning: '国际', example: 'This is an international event.' },
  { text: 'just', meaning: '公正', example: 'That was the just decision.' },
  { text: 'keen', meaning: '热切', example: 'He is keen on learning languages.' },
  { text: 'last', meaning: '最后', example: 'That was the last time I saw him.' },
  { text: 'late', meaning: '迟', example: 'You are late for the meeting.' },
  { text: 'left', meaning: '左', example: 'Turn left at the next corner.' },
  { text: 'less', meaning: '较少', example: 'Use less sugar in your tea.' },
  { text: 'level', meaning: '水平', example: 'Keep the water at this level.' },
  { text: 'light', meaning: '轻', example: 'This bag is light to carry.' },
  { text: 'likely', meaning: '可能', example: 'It is likely to rain today.' },
  { text: 'limited', meaning: '有限', example: 'We have limited time today.' },
  { text: 'liquid', meaning: '液体', example: 'Water is a clear liquid.' },
  { text: 'little', meaning: '小', example: 'I have a little dog at home.' },
  { text: 'local', meaning: '当地', example: 'The local store is very near.' },
  { text: 'long', meaning: '长', example: 'The road is very long and straight.' },
  { text: 'loose', meaning: '松', example: 'The rope is loose and will fall.' },
  { text: 'low', meaning: '低', example: 'The temperature is very low today.' },
  { text: 'lucky', meaning: '幸运', example: 'I am lucky to have good friends.' },
  { text: 'main', meaning: '主要', example: 'What is the main reason for this?' },
  { text: 'major', meaning: '重大', example: 'That was a major change for us.' },
  { text: 'male', meaning: '男性', example: 'He is the only male in the group.' },
  { text: 'married', meaning: '已婚', example: 'They got married last year.' },
  { text: 'material', meaning: '材料', example: 'What material is this made of?' },
  { text: 'maximum', meaning: '最大', example: 'The maximum speed is one hundred.' },
  { text: 'medical', meaning: '医学', example: 'She needs medical help now.' },
  { text: 'mental', meaning: '精神', example: 'He has good mental health.' },
  { text: 'mild', meaning: '温和', example: 'The weather is mild today.' },
  { text: 'military', meaning: '军事', example: 'He served in the military for years.' },
  { text: 'minimum', meaning: '最小', example: 'The minimum age is eighteen.' },
  { text: 'modern', meaning: '现代', example: 'This is a very modern building.' },
  { text: 'moral', meaning: '道德', example: 'That is the moral thing to do.' },
  { text: 'more', meaning: '更多', example: 'Give me more time to finish.' },
  { text: 'most', meaning: '最多', example: 'Most people like good food.' },
  { text: 'much', meaning: '很多', example: 'Thank you very much for this.' },
  { text: 'narrow', meaning: '窄', example: 'The street is very narrow here.' },
  { text: 'national', meaning: '国家', example: 'This is a national holiday today.' },
  { text: 'natural', meaning: '自然', example: 'It is natural to feel this way.' },
  { text: 'near', meaning: '近', example: 'The school is very near to us.' },
  { text: 'neat', meaning: '整洁', example: 'Her room is always neat and clean.' },
  { text: 'necessary', meaning: '必要', example: 'Sleep is necessary for health.' },
  { text: 'new', meaning: '新', example: 'I bought a new book today.' },
  { text: 'next', meaning: '下一个', example: 'See me next Monday morning.' },
  { text: 'nice', meaning: '好', example: 'That is a very nice dress.' },
  { text: 'normal', meaning: '正常', example: 'Everything is back to normal.' },
  { text: 'north', meaning: '北方', example: 'The wind comes from the north.' },
  { text: 'noted', meaning: '著名', example: 'He is a noted artist in this city.' },
  { text: 'obvious', meaning: '明显', example: 'That is the obvious answer.' },
  { text: 'odd', meaning: '奇怪', example: 'That was an odd thing to say.' },
  { text: 'old', meaning: '老', example: 'My grandfather is very old.' },
  { text: 'opposite', meaning: '相反', example: 'They live on the opposite side.' },
  { text: 'ordinary', meaning: '普通', example: 'This is just an ordinary day.' },
  { text: 'organized', meaning: '有组织', example: 'She is a very organized person.' },
  { text: 'other', meaning: '其他', example: 'All the other books are new.' },
  { text: 'own', meaning: '自己的', example: 'I have my own room now.' },
  { text: 'particular', meaning: '特定', example: 'Is there a particular reason?' },
  { text: 'past', meaning: '过去', example: 'In the past we lived here.' },
  { text: 'personal', meaning: '个人', example: 'This is my personal opinion.' },
  { text: 'plain', meaning: '简单', example: 'Give me a plain answer.' },
  { text: 'pleasant', meaning: '愉快', example: 'We had a pleasant time today.' },
  { text: 'pleased', meaning: '高兴', example: 'I am pleased with the result.' },
  { text: 'political', meaning: '政治', example: 'That is a political question.' },
  { text: 'poor', meaning: '穷', example: 'They were poor when young.' },
  { text: 'popular', meaning: '受欢迎', example: 'This song is very popular.' },
  { text: 'positive', meaning: '积极', example: 'Try to have a positive mind.' },
  { text: 'possible', meaning: '可能', example: 'It is possible to finish on time.' },
  { text: 'powerful', meaning: '强大', example: 'That is a very powerful machine.' },
  { text: 'present', meaning: '目前', example: 'At the present time we are safe.' },
  { text: 'previous', meaning: '之前', example: 'The previous owner was kind.' },
  { text: 'primary', meaning: '主要', example: 'This is the primary reason.' },
  { text: 'private', meaning: '私人', example: 'This is my private space now.' },
  { text: 'progress', meaning: '进步', example: 'You are making good progress.' },
  { text: 'proper', meaning: '适当', example: 'Use the proper tool for this.' },
  { text: 'public', meaning: '公共', example: 'This is a public park for all.' },
  { text: 'pure', meaning: '纯', example: 'This is pure water from the well.' },
  { text: 'quick', meaning: '快', example: 'Give me a quick answer now.' },
  { text: 'quiet', meaning: '安静', example: 'Please be quiet in the library.' },
  { text: 'rapid', meaning: '迅速', example: 'There has been rapid growth.' },
  { text: 'ready', meaning: '准备好', example: 'Are you ready to go now?' },
  { text: 'real', meaning: '真实', example: 'Is this a real diamond ring?' },
  { text: 'reasonable', meaning: '合理', example: 'That is a reasonable price.' },
  { text: 'recent', meaning: '最近', example: 'I saw him in recent days.' },
  { text: 'red', meaning: '红色', example: 'She wore a red dress today.' },
  { text: 'regular', meaning: '规律', example: 'Take regular exercise every day.' },
  { text: 'responsible', meaning: '负责', example: 'He is responsible for this work.' },
  { text: 'rich', meaning: '富有', example: 'She comes from a rich family.' },
  { text: 'right', meaning: '正确', example: 'You are right about this matter.' },
  { text: 'rough', meaning: '粗糙', example: 'The road is rough and bumpy.' },
  { text: 'round', meaning: '圆', example: 'The table is round in shape.' },
  { text: 'sad', meaning: '悲伤', example: 'She looked very sad today.' },
  { text: 'safe', meaning: '安全', example: 'The children are safe at home.' },
  { text: 'same', meaning: '相同', example: 'We wear the same color today.' },
  { text: 'satisfied', meaning: '满意', example: 'I am satisfied with the work.' },
  { text: 'secret', meaning: '秘密', example: 'Keep this as a secret between us.' },
  { text: 'serious', meaning: '严肃', example: 'This is a very serious matter.' },
  { text: 'sharp', meaning: '锋利', example: 'Be careful, the knife is sharp.' },
  { text: 'short', meaning: '短', example: 'This road is short and easy.' },
  { text: 'shut', meaning: '关闭', example: 'Please shut the door behind you.' },
  { text: 'sick', meaning: '生病', example: 'He is too sick to go to work.' },
  { text: 'simple', meaning: '简单', example: 'The answer is very simple.' },
  { text: 'single', meaning: '单一', example: 'This is the single best way.' },
  { text: 'slow', meaning: '慢', example: 'Please drive slow on this road.' },
  { text: 'small', meaning: '小', example: 'I live in a small but nice house.' },
  { text: 'smart', meaning: '聪明', example: 'She is a very smart student.' },
  { text: 'soft', meaning: '软', example: 'This pillow is very soft.' },
  { text: 'solid', meaning: '固体', example: 'Water becomes solid when frozen.' },
  { text: 'sorry', meaning: '对不起', example: 'I am sorry I was late today.' },
  { text: 'south', meaning: '南方', example: 'The birds fly south in winter.' },
  { text: 'spare', meaning: '备用', example: 'Do you have a spare key?' },
  { text: 'special', meaning: '特别', example: 'Today is a very special day.' },
  { text: 'standard', meaning: '标准', example: 'This is the standard way to do it.' },
  { text: 'steady', meaning: '稳定', example: 'Keep a steady speed while driving.' },
  { text: 'strange', meaning: '奇怪', example: 'That was a strange thing to see.' },
  { text: 'strong', meaning: '强壮', example: 'He is a very strong man.' },
  { text: 'sudden', meaning: '突然', example: 'There was a sudden loud noise.' },
  { text: 'suitable', meaning: '合适', example: 'This is suitable for all ages.' },
  { text: 'sure', meaning: '确定', example: 'I am sure about this answer.' },
  { text: 'sweet', meaning: '甜', example: 'This fruit is very sweet to eat.' },
  { text: 'tall', meaning: '高', example: 'That building is very tall indeed.' },
  { text: 'tender', meaning: '温柔', example: 'She spoke in a tender voice.' },
  { text: 'terrible', meaning: '可怕', example: 'That was a terrible accident.' },
  { text: 'thick', meaning: '厚', example: 'This book is very thick and heavy.' },
  { text: 'tight', meaning: '紧', example: 'The lid is too tight to open.' },
  { text: 'tiny', meaning: '极小', example: 'The baby has tiny little hands.' },
  { text: 'tired', meaning: '累', example: 'I am very tired after work.' },
  { text: 'total', meaning: '总共', example: 'What is the total cost of this?' },
  { text: 'tough', meaning: '坚韧', example: 'This material is very tough.' },
  { text: 'true', meaning: '真实', example: 'That is a true story about me.' },
  { text: 'typical', meaning: '典型', example: 'This is a typical day at work.' },
  { text: 'ugly', meaning: '丑', example: 'That is an ugly building indeed.' },
  { text: 'uncertain', meaning: '不确定', example: 'The future is uncertain for all.' },
  { text: 'under', meaning: '在…下', example: 'The cat is under the table now.' },
  { text: 'unfortunate', meaning: '不幸', example: 'That was an unfortunate event.' },
  { text: 'unique', meaning: '独特', example: 'Every person is unique and special.' },
  { text: 'united', meaning: '联合', example: 'They are united as one group.' },
  { text: 'unlikely', meaning: '不太可能', example: 'It is unlikely to snow today.' },
  { text: 'usual', meaning: '通常', example: 'I take the usual bus to work.' },
  { text: 'various', meaning: '各种', example: 'There are various kinds of food.' },
  { text: 'violent', meaning: '暴力', example: 'The storm was very violent today.' },
  { text: 'visible', meaning: '可见', example: 'The stars are visible tonight.' },
  { text: 'vital', meaning: '重要', example: 'Water is vital for all life.' },
  { text: 'warm', meaning: '温暖', example: 'The room is nice and warm today.' },
  { text: 'weak', meaning: '弱', example: 'He felt weak after the long illness.' },
  { text: 'well', meaning: '好', example: 'She speaks very well in public.' },
  { text: 'west', meaning: '西方', example: 'The sun goes down in the west.' },
  { text: 'white', meaning: '白色', example: 'The snow is white and clean.' },
  { text: 'wide', meaning: '宽', example: 'The river is very wide at this point.' },
  { text: 'wild', meaning: '野生', example: 'There are wild animals in the forest.' },
  { text: 'wise', meaning: '明智', example: 'That was a very wise decision.' },
  { text: 'wrong', meaning: '错误', example: 'You gave the wrong answer to me.' },
  { text: 'ability', meaning: '能力', example: 'She has the ability to lead.' },
  { text: 'absence', meaning: '缺席', example: 'His absence was noted by all.' },
  { text: 'addition', meaning: '添加', example: 'This is a good addition to the plan.' },
  { text: 'adventure', meaning: '冒险', example: 'The trip was a great adventure.' },
  { text: 'advice', meaning: '建议', example: 'He gave me some good advice.' },
  { text: 'age', meaning: '年龄', example: 'What is your age in years?' },
  { text: 'aim', meaning: '目标', example: 'What is your aim in life?' },
  { text: 'alarm', meaning: '警报', example: 'The alarm went off at six.' },
  { text: 'anger', meaning: '愤怒', example: 'He showed his anger at the news.' },
  { text: 'anxiety', meaning: '焦虑', example: 'She felt great anxiety before the test.' },
  { text: 'area', meaning: '地区', example: 'This area is very quiet at night.' },
  { text: 'argument', meaning: '争论', example: 'We had a big argument about this.' },
  { text: 'battle', meaning: '战斗', example: 'The battle lasted for many hours.' },

  // ── Abstract Words (435) ──
  { text: 'beauty', meaning: '美丽', example: 'The beauty of the sunset was great.' },
  { text: 'blessing', meaning: '祝福', example: 'Having family is a blessing.' },
  { text: 'business', meaning: '商业', example: 'Business is good this year.' },
  { text: 'capacity', meaning: '容量', example: 'The capacity of the room is fifty.' },
  { text: 'cause', meaning: '原因', example: 'What is the cause of this problem?' },
  { text: 'change', meaning: '变化', example: 'Change is always a good thing.' },
  { text: 'charge', meaning: '负责', example: 'Who is in charge of this project?' },
  { text: 'cheer', meaning: '欢呼', example: 'Give a cheer for the team now.' },
  { text: 'choice', meaning: '选择', example: 'You have a choice to make here.' },
  { text: 'comparison', meaning: '比较', example: 'There is no comparison between them.' },
  { text: 'competition', meaning: '竞争', example: 'The competition was very hard.' },
  { text: 'concern', meaning: '关心', example: 'That is my main concern right now.' },
  { text: 'condition', meaning: '条件', example: 'The condition of the house is good.' },
  { text: 'connection', meaning: '联系', example: 'There is a connection between the two.' },
  { text: 'consideration', meaning: '考虑', example: 'Give this careful consideration.' },
  { text: 'construction', meaning: '建设', example: 'The construction of the road is done.' },
  { text: 'contact', meaning: '联系', example: 'Keep in contact with your friends.' },
  { text: 'contract', meaning: '合同', example: 'Sign the contract before you start.' },
  { text: 'conversation', meaning: '对话', example: 'We had a nice conversation.' },
  { text: 'corner', meaning: '角落', example: 'Turn at the corner of the street.' },
  { text: 'courage', meaning: '勇气', example: 'You need courage to do this.' },
  { text: 'creation', meaning: '创造', example: 'This is a work of great creation.' },
  { text: 'crisis', meaning: '危机', example: 'We must act in this crisis now.' },
  { text: 'criticism', meaning: '批评', example: 'The criticism was not very kind.' },
  { text: 'custom', meaning: '习俗', example: 'This custom is very old here.' },
  { text: 'date', meaning: '日期', example: 'What is the date of the meeting?' },
  { text: 'deal', meaning: '交易', example: 'That is a good deal for both of us.' },
  { text: 'debate', meaning: '辩论', example: 'The debate lasted two hours.' },
  { text: 'debt', meaning: '债务', example: 'He has a large debt to pay off.' },
  { text: 'decision', meaning: '决定', example: 'Make your decision before Friday.' },
  { text: 'defeat', meaning: '失败', example: 'The defeat was a hard one to take.' },
  { text: 'defense', meaning: '防御', example: 'The defense of the city was strong.' },
  { text: 'degree', meaning: '程度', example: 'A high degree of skill is needed.' },
  { text: 'demand', meaning: '需求', example: 'The demand for this product is high.' },
  { text: 'description', meaning: '描述', example: 'Give me a clear description of him.' },
  { text: 'direction', meaning: '方向', example: 'In which direction should we go?' },
  { text: 'discovery', meaning: '发现', example: 'The discovery was made last year.' },
  { text: 'discussion', meaning: '讨论', example: 'We had a good discussion about it.' },
  { text: 'distance', meaning: '距离', example: 'The distance is about two miles.' },
  { text: 'disturbance', meaning: '打扰', example: 'Sorry for the disturbance today.' },
  { text: 'doubt', meaning: '怀疑', example: 'There is no doubt about this.' },
  { text: 'dream', meaning: '梦', example: 'I had a strange dream last night.' },
  { text: 'duty', meaning: '责任', example: 'It is my duty to help you.' },
  { text: 'earth', meaning: '地球', example: 'The earth goes around the sun.' },
  { text: 'edge', meaning: '边缘', example: 'Be careful at the edge of the cliff.' },
  { text: 'education', meaning: '教育', example: 'Education is important for all.' },
  { text: 'effort', meaning: '努力', example: 'It took a lot of effort to finish.' },
  { text: 'emotion', meaning: '情感', example: 'Love is a strong emotion in life.' },
  { text: 'energy', meaning: '精力', example: 'She has a lot of energy today.' },
  { text: 'example', meaning: '例子', example: 'Give me an example of your work.' },
  { text: 'exchange', meaning: '交换', example: 'We made an exchange of ideas.' },
  { text: 'excitement', meaning: '兴奋', example: 'The excitement of the game was great.' },
  { text: 'experience', meaning: '经验', example: 'He has much experience in this field.' },
  { text: 'expression', meaning: '表达', example: 'His expression was very kind.' },
  { text: 'failure', meaning: '失败', example: 'Failure is a part of life.' },
  { text: 'faith', meaning: '信念', example: 'I have faith in your ability.' },
  { text: 'fame', meaning: '名声', example: 'He gained fame for his work.' },
  { text: 'favor', meaning: '帮助', example: 'Can you do me a favor now?' },
  { text: 'feeling', meaning: '感觉', example: 'I have a good feeling about this.' },
  { text: 'figure', meaning: '数字', example: 'What are the figures for this year?' },
  { text: 'force', meaning: '力量', example: 'Use force to open the door.' },
  { text: 'form', meaning: '形式', example: 'Fill out this form before you go.' },
  { text: 'freedom', meaning: '自由', example: 'Freedom is important to every person.' },
  { text: 'future', meaning: '未来', example: 'The future looks very bright for us.' },
  { text: 'gain', meaning: '获得', example: 'You will gain much from this work.' },
  { text: 'goal', meaning: '目标', example: 'What is your main goal in life?' },
  { text: 'grace', meaning: '优雅', example: 'She moves with great grace and poise.' },
  { text: 'growth', meaning: '增长', example: 'The growth of the company is fast.' },
  { text: 'guide', meaning: '指南', example: 'This book is a good guide for all.' },
  { text: 'habit', meaning: '习惯', example: 'It is a good habit to read every day.' },
  { text: 'harm', meaning: '伤害', example: 'There is no harm in trying this.' },
  { text: 'harvest', meaning: '收获', example: 'The harvest was very good this year.' },
  { text: 'health', meaning: '健康', example: 'Good health is important for life.' },
  { text: 'heat', meaning: '热', example: 'The heat of the sun is very strong.' },
  { text: 'help', meaning: '帮助', example: 'Can you give me some help today?' },
  { text: 'history', meaning: '历史', example: 'We study history at school.' },
  { text: 'hope', meaning: '希望', example: 'I have hope for a better future.' },
  { text: 'humor', meaning: '幽默', example: 'He has a great sense of humor.' },
  { text: 'hurry', meaning: '匆忙', example: 'Why are you in such a hurry today?' },
  { text: 'idea', meaning: '想法', example: 'That is a very good idea indeed.' },
  { text: 'imagination', meaning: '想象力', example: 'She has a great imagination.' },
  { text: 'importance', meaning: '重要性', example: 'The importance of this is great.' },
  { text: 'impression', meaning: '印象', example: 'You made a good impression on me.' },
  { text: 'independence', meaning: '独立', example: 'She values her independence greatly.' },
  { text: 'influence', meaning: '影响', example: 'He has a strong influence on others.' },
  { text: 'interest', meaning: '兴趣', example: 'I have a great interest in music.' },
  { text: 'intention', meaning: '意图', example: 'My intention is to help you all.' },
  { text: 'iron', meaning: '铁', example: 'The gate is made of iron metal.' },
  { text: 'joy', meaning: '欢乐', example: 'The birth of the baby brought joy.' },
  { text: 'judgment', meaning: '判断', example: 'Use good judgment in this matter.' },
  { text: 'justice', meaning: '正义', example: 'Justice must be done for all people.' },
  { text: 'knowledge', meaning: '知识', example: 'His knowledge of this subject is great.' },
  { text: 'lack', meaning: '缺乏', example: 'There is a lack of clean water here.' },
  { text: 'law', meaning: '法律', example: 'Every person must follow the law.' },
  { text: 'leadership', meaning: '领导力', example: 'She has great leadership ability.' },
  { text: 'league', meaning: '联盟', example: 'They joined the same league together.' },
  { text: 'length', meaning: '长度', example: 'The length of the road is five miles.' },
  { text: 'lesson', meaning: '课', example: 'We learned a good lesson today.' },
  { text: 'liberty', meaning: '自由', example: 'Liberty is important to all people.' },
  { text: 'life', meaning: '生命', example: 'Life is full of good surprises.' },
  { text: 'limit', meaning: '限制', example: 'There is a limit to what we can do.' },
  { text: 'line', meaning: '线', example: 'Draw a straight line on the paper.' },
  { text: 'loss', meaning: '损失', example: 'The loss of the game was very sad.' },
  { text: 'love', meaning: '爱', example: 'Love is the strongest emotion.' },
  { text: 'luck', meaning: '运气', example: 'Good luck with your new job.' },
  { text: 'mark', meaning: '记号', example: 'Put a mark on the right answer.' },
  { text: 'mass', meaning: '大量', example: 'There was a mass of people at the gate.' },
  { text: 'measure', meaning: '测量', example: 'Measure the room before you buy.' },
  { text: 'memory', meaning: '记忆', example: 'I have a good memory of that day.' },
  { text: 'message', meaning: '信息', example: 'Leave a message for me here.' },
  { text: 'method', meaning: '方法', example: 'This method works very well for me.' },
  { text: 'mind', meaning: '头脑', example: 'A good mind is a terrible thing to waste.' },
  { text: 'moment', meaning: '时刻', example: 'Wait just a moment for me please.' },
  { text: 'money', meaning: '钱', example: 'How much money do you have now?' },
  { text: 'motion', meaning: '运动', example: 'The motion of the car was very smooth.' },
  { text: 'music', meaning: '音乐', example: 'I like to listen to good music.' },
  { text: 'mystery', meaning: '谜', example: 'The mystery was solved at last.' },
  { text: 'nature', meaning: '自然', example: 'I love the beauty of nature.' },
  { text: 'need', meaning: '需要', example: 'There is no need to hurry now.' },
  { text: 'nerve', meaning: '神经', example: 'You need a lot of nerve to do this.' },
  { text: 'note', meaning: '笔记', example: 'Write a note to remind me.' },
  { text: 'notice', meaning: '注意', example: 'Did you notice the sign on the door?' },
  { text: 'number', meaning: '数字', example: 'Give me the number for the taxi.' },
  { text: 'object', meaning: '物体', example: 'What is that object on the table?' },
  { text: 'obligation', meaning: '义务', example: 'It is my obligation to help others.' },
  { text: 'observation', meaning: '观察', example: 'Your observation is very important.' },
  { text: 'occasion', meaning: '场合', example: 'This is a very special occasion for us.' },
  { text: 'offer', meaning: '提议', example: 'That is a good offer for the house.' },
  { text: 'order', meaning: '秩序', example: 'Everything is in good order now.' },
  { text: 'pain', meaning: '疼痛', example: 'I felt a sharp pain in my head.' },
  { text: 'pair', meaning: '一对', example: 'I need a new pair of shoes.' },
  { text: 'passage', meaning: '通道', example: 'The passage between the rooms is short.' },
  { text: 'patience', meaning: '耐心', example: 'You need patience to teach a child.' },
  { text: 'pattern', meaning: '模式', example: 'I like the pattern on this cloth.' },
  { text: 'peace', meaning: '和平', example: 'We all want peace in the world.' },
  { text: 'percent', meaning: '百分比', example: 'Fifty percent of the people came.' },
  { text: 'performance', meaning: '表现', example: 'Your performance was very good.' },
  { text: 'period', meaning: '时期', example: 'This was a good period in our life.' },
  { text: 'permission', meaning: '允许', example: 'Do I have permission to go now?' },
  { text: 'pleasure', meaning: '快乐', example: 'It was a pleasure to meet you.' },
  { text: 'plenty', meaning: '大量', example: 'We have plenty of time to finish.' },
  { text: 'point', meaning: '点', example: 'What is the main point of this story?' },
  { text: 'position', meaning: '位置', example: 'What is your position on this matter?' },
  { text: 'possibility', meaning: '可能性', example: 'There is a possibility of rain today.' },
  { text: 'power', meaning: '力量', example: 'Knowledge is a form of power.' },
  { text: 'practice', meaning: '练习', example: 'Practice makes perfect in any skill.' },
  { text: 'praise', meaning: '赞扬', example: 'He received much praise for his work.' },
  { text: 'prayer', meaning: '祈祷', example: 'She said a prayer before the meal.' },
  { text: 'pride', meaning: '骄傲', example: 'She takes great pride in her work.' },
  { text: 'principle', meaning: '原则', example: 'He always acts on principle.' },
  { text: 'promise', meaning: '承诺', example: 'I give you my promise to be kind.' },
  { text: 'property', meaning: '财产', example: 'This property belongs to our family.' },
  { text: 'proposal', meaning: '建议', example: 'The proposal was accepted by all.' },
  { text: 'protection', meaning: '保护', example: 'This coat gives you protection from rain.' },
  { text: 'purpose', meaning: '目的', example: 'What is the purpose of this meeting?' },
  { text: 'quality', meaning: '质量', example: 'The quality of this product is very good.' },
  { text: 'quantity', meaning: '数量', example: 'What quantity do you need to buy?' },
  { text: 'range', meaning: '范围', example: 'The range of choices is very wide.' },
  { text: 'rate', meaning: '比率', example: 'What is the rate of growth here?' },
  { text: 'reaction', meaning: '反应', example: 'What was your reaction to the news?' },
  { text: 'reason', meaning: '原因', example: 'Give me a good reason for this.' },
  { text: 'reference', meaning: '参考', example: 'Use this book as your reference.' },
  { text: 'relation', meaning: '关系', example: 'We have a good relation with them.' },
  { text: 'remains', meaning: '残余', example: 'The remains of the old house were sad.' },
  { text: 'respect', meaning: '尊重', example: 'Show respect to the older people.' },
  { text: 'result', meaning: '结果', example: 'The result was better than expected.' },
  { text: 'reward', meaning: '奖励', example: 'He got a reward for good work.' },
  { text: 'role', meaning: '角色', example: 'She played a big role in this project.' },
  { text: 'rule', meaning: '规则', example: 'Every person must follow the rule.' },
  { text: 'safety', meaning: '安全', example: 'Safety is the most important thing.' },
  { text: 'satisfaction', meaning: '满意', example: 'He looked at his work with satisfaction.' },
  { text: 'scale', meaning: '规模', example: 'The scale of the project is very big.' },
  { text: 'section', meaning: '部分', example: 'This section of the book is interesting.' },
  { text: 'selection', meaning: '选择', example: 'The selection of candidates was good.' },
  { text: 'service', meaning: '服务', example: 'The service at this hotel is great.' },
  { text: 'share', meaning: '份额', example: 'What is my share of the total cost?' },
  { text: 'sign', meaning: '迹象', example: 'There is no sign of the storm yet.' },
  { text: 'silence', meaning: '沉默', example: 'The silence in the room was deep.' },
  { text: 'skill', meaning: '技能', example: 'She has a great skill in painting.' },
  { text: 'sleep', meaning: '睡眠', example: 'I need eight hours of sleep each night.' },
  { text: 'society', meaning: '社会', example: 'We all live in the same society.' },
  { text: 'solution', meaning: '解决', example: 'We found a good solution to the problem.' },
  { text: 'soul', meaning: '灵魂', example: 'Music touches the soul of a person.' },
  { text: 'spirit', meaning: '精神', example: 'He has a good spirit in life.' },
  { text: 'strength', meaning: '力量', example: 'She has the strength to carry on.' },
  { text: 'struggle', meaning: '奋斗', example: 'The struggle for peace goes on.' },
  { text: 'success', meaning: '成功', example: 'Success comes to those who work hard.' },
  { text: 'suffering', meaning: '痛苦', example: 'The suffering of the people was great.' },
  { text: 'symbol', meaning: '象征', example: 'The dove is a symbol of peace.' },
  { text: 'talent', meaning: '才能', example: 'She has a great talent for music.' },
  { text: 'taste', meaning: '品味', example: 'He has very good taste in art.' },
  { text: 'tendency', meaning: '趋势', example: 'There is a tendency for prices to rise.' },
  { text: 'thought', meaning: '想法', example: 'That was a good thought from you.' },
  { text: 'tide', meaning: '潮水', example: 'The tide comes in twice a day.' },
  { text: 'time', meaning: '时间', example: 'Time is very precious for all of us.' },
  { text: 'title', meaning: '标题', example: 'What is the title of this book?' },
  { text: 'tone', meaning: '语气', example: 'He spoke in a soft and kind tone.' },
  { text: 'trade', meaning: '贸易', example: 'Trade between the two countries is good.' },
  { text: 'tradition', meaning: '传统', example: 'This tradition is very old here.' },
  { text: 'treatment', meaning: '对待', example: 'He received good treatment at the hospital.' },
  { text: 'trend', meaning: '趋势', example: 'There is a new trend in fashion.' },
  { text: 'trust', meaning: '信任', example: 'I have trust in my good friends.' },
  { text: 'turn', meaning: '转弯', example: 'Take a right turn at the corner.' },
  { text: 'union', meaning: '联合', example: 'The union of the two groups was good.' },
  { text: 'value', meaning: '价值', example: 'The value of this painting is high.' },
  { text: 'variety', meaning: '多样性', example: 'A variety of food is on the table.' },
  { text: 'victory', meaning: '胜利', example: 'The victory was celebrated by all.' },
  { text: 'violence', meaning: '暴力', example: 'We must stop all forms of violence.' },
  { text: 'volume', meaning: '音量', example: 'Turn the volume up on the radio.' },
  { text: 'wage', meaning: '工资', example: 'What is the hourly wage for this job?' },
  { text: 'war', meaning: '战争', example: 'War brings much suffering to people.' },
  { text: 'warning', meaning: '警告', example: 'The warning came just in time for us.' },
  { text: 'wealth', meaning: '财富', example: 'True wealth is having good health.' },
  { text: 'weapon', meaning: '武器', example: 'The weapon was found by the army.' },
  { text: 'weight', meaning: '重量', example: 'What is the weight of this bag?' },
  { text: 'welcome', meaning: '欢迎', example: 'You are welcome in our home always.' },
  { text: 'welfare', meaning: '福利', example: 'The welfare of the people is important.' },
  { text: 'will', meaning: '意志', example: 'She has a very strong will in life.' },
  { text: 'wish', meaning: '愿望', example: 'My wish is to travel the world.' },
  { text: 'wonder', meaning: '惊奇', example: 'I wonder what the future will bring.' },
  { text: 'work', meaning: '工作', example: 'Hard work is the key to success.' },
  { text: 'world', meaning: '世界', example: 'The world is a beautiful place to live.' },
  { text: 'year', meaning: '年', example: 'This has been a good year for us.' },
  { text: 'youth', meaning: '青春', example: 'Youth is a time of great energy.' },
  { text: 'accord', meaning: '一致', example: 'They came to an accord on the deal.' },
  { text: 'across', meaning: '穿过', example: 'He walked across the street safely.' },
  { text: 'address', meaning: '地址', example: 'What is your home address?' },
  { text: 'admit', meaning: '承认', example: 'He did admit his mistake at last.' },
  { text: 'advance', meaning: '前进', example: 'We must advance with the times.' },
  { text: 'against', meaning: '反对', example: 'They are against the new plan.' },
  { text: 'air', meaning: '空气', example: 'The air here is very clean and fresh.' },
  { text: 'anyone', meaning: '任何人', example: 'Anyone can learn to read and write.' },
  { text: 'asleep', meaning: '睡着', example: 'The baby fell asleep quickly.' },
  { text: 'ate', meaning: '吃了', example: 'She ate her breakfast at seven.' },
  { text: 'become', meaning: '成为', example: 'She wants to become a doctor.' },
  { text: 'begin', meaning: '开始', example: 'Let us begin the meeting now.' },
  { text: 'behave', meaning: '表现', example: 'Please behave well in the class.' },
  { text: 'belong', meaning: '属于', example: 'This book belongs to my friend.' },
  { text: 'beside', meaning: '旁边', example: 'Come and sit beside me here.' },
  { text: 'beyond', meaning: '超出', example: 'The beauty is beyond all description.' },
  { text: 'bind', meaning: '绑', example: 'Bind the books with a strong rope.' },
  { text: 'bite', meaning: '咬', example: 'The dog might bite if provoked.' },
  { text: 'block', meaning: '街区', example: 'The store is two blocks from here.' },
  { text: 'boil', meaning: '沸腾', example: 'Heat the water until it starts to boil.' },
  { text: 'borrow', meaning: '借', example: 'Can I borrow your pen for a minute?' },
  { text: 'breed', meaning: '品种', example: 'What breed of dog is this one?' },
  { text: 'bring', meaning: '带来', example: 'Please bring your book to class.' },
  { text: 'brush', meaning: '刷', example: 'Brush your teeth twice every day.' },
  { text: 'bucket', meaning: '桶', example: 'Fill the bucket with clean water.' },
  { text: 'build', meaning: '建造', example: 'They will build a new school here.' },
  { text: 'cage', meaning: '笼子', example: 'The bird is inside the cage now.' },
  { text: 'calculate', meaning: '计算', example: 'Can you calculate the total cost?' },
  { text: 'capture', meaning: '捕获', example: 'The army managed to capture the town.' },
  { text: 'carry', meaning: '携带', example: 'Can you carry this bag for me?' },
  { text: 'catch', meaning: '抓住', example: 'Try to catch the ball with both hands.' },
  { text: 'celebrate', meaning: '庆祝', example: 'We celebrate birthdays with a cake.' },
  { text: 'choose', meaning: '选择', example: 'Choose the one you like the most.' },
  { text: 'claim', meaning: '声称', example: 'He did claim to know the answer.' },
  { text: 'climb', meaning: '攀登', example: 'We will climb the mountain tomorrow.' },
  { text: 'collect', meaning: '收集', example: 'She likes to collect old books.' },
  { text: 'combine', meaning: '结合', example: 'Combine the two things into one.' },
  { text: 'commit', meaning: '承诺', example: 'He did commit to helping the team.' },
  { text: 'compare', meaning: '比较', example: 'Compare the two prices before buying.' },
  { text: 'connect', meaning: '连接', example: 'Connect the wire to the machine.' },
  { text: 'consider', meaning: '考虑', example: 'Please consider my offer carefully.' },
  { text: 'contain', meaning: '包含', example: 'The box contains ten small items.' },
  { text: 'contribute', meaning: '贡献', example: 'Everyone should contribute to the plan.' },
  { text: 'convince', meaning: '说服', example: 'I tried to convince him to come.' },
  { text: 'count', meaning: '计数', example: 'Count the money and tell me the total.' },
  { text: 'crash', meaning: '碰撞', example: 'The car crashed into a big tree.' },
  { text: 'create', meaning: '创造', example: 'She can create beautiful things from art.' },
  { text: 'cut', meaning: '切', example: 'Cut the bread into small pieces.' },
  { text: 'dance', meaning: '跳舞', example: 'They like to dance to the music.' },
  { text: 'decide', meaning: '决定', example: 'Decide what you want to do first.' },
  { text: 'deliver', meaning: '递送', example: 'They will deliver the package today.' },
  { text: 'describe', meaning: '描述', example: 'Can you describe what you saw?' },
  { text: 'deserve', meaning: '值得', example: 'She does deserve this good reward.' },
  { text: 'destroy', meaning: '毁坏', example: 'The storm could destroy many buildings.' },
  { text: 'develop', meaning: '发展', example: 'We must develop new ideas and plans.' },
  { text: 'die', meaning: '死亡', example: 'Plants will die without water and light.' },
  { text: 'dig', meaning: '挖', example: 'Dig a deep hole in the ground here.' },
  { text: 'divide', meaning: '分开', example: 'Divide the food equally among all.' },
  { text: 'draw', meaning: '画', example: 'She can draw very well with a pen.' },
  { text: 'earn', meaning: '赚', example: 'She works hard to earn good money.' },
  { text: 'educate', meaning: '教育', example: 'We must educate all the young children.' },
  { text: 'elect', meaning: '选举', example: 'They will elect a new leader soon.' },
  { text: 'employ', meaning: '雇用', example: 'The company will employ many new people.' },
  { text: 'encourage', meaning: '鼓励', example: 'We must encourage the children to learn.' },
  { text: 'enjoy', meaning: '享受', example: 'I enjoy spending time with my family.' },
  { text: 'enter', meaning: '进入', example: 'Please enter the room quietly now.' },
  { text: 'escape', meaning: '逃跑', example: 'The bird tried to escape from the cage.' },
  { text: 'examine', meaning: '检查', example: 'The doctor will examine you tomorrow.' },
  { text: 'exercise', meaning: '锻炼', example: 'Take exercise every day to stay fit.' },
  { text: 'exist', meaning: '存在', example: 'Do you believe ghosts really exist?' },
  { text: 'expect', meaning: '期望', example: 'I expect to see you at the meeting.' },
  { text: 'explain', meaning: '解释', example: 'Can you explain this to me again?' },
  { text: 'explore', meaning: '探索', example: 'They want to explore the deep ocean.' },
  { text: 'express', meaning: '表达', example: 'How do you express your feelings?' },
  { text: 'face', meaning: '面对', example: 'We must face the truth together.' },
  { text: 'fight', meaning: '战斗', example: 'The two children fight over small things.' },
  { text: 'fill', meaning: '填满', example: 'Please fill the glass with cold water.' },
  { text: 'find', meaning: '找到', example: 'Try to find the lost key in the house.' },
  { text: 'float', meaning: '漂浮', example: 'Wood can float on top of the water.' },
  { text: 'flow', meaning: '流动', example: 'The river flows from the mountain down.' },
  { text: 'fold', meaning: '折叠', example: 'Fold the cloth and put it in the box.' },
  { text: 'follow', meaning: '跟随', example: 'Follow me and I will show the way.' },
  { text: 'freeze', meaning: '结冰', example: 'Water will freeze when it gets cold.' },
  { text: 'hang', meaning: '挂', example: 'Hang your coat on the hook by the door.' },
  { text: 'happen', meaning: '发生', example: 'What happened at school today?' },
  { text: 'hate', meaning: '讨厌', example: 'I hate getting up early in the morning.' },
  { text: 'hear', meaning: '听到', example: 'Can you hear the sound of the music?' },
  { text: 'hide', meaning: '躲藏', example: 'The children like to hide behind the door.' },
  { text: 'hunt', meaning: '打猎', example: 'The cat will hunt for a small mouse.' },
  { text: 'hurt', meaning: '受伤', example: 'Be careful or you will hurt yourself.' },
  { text: 'imagine', meaning: '想象', example: 'Imagine you are in a beautiful garden.' },
  { text: 'include', meaning: '包括', example: 'The price does include the tax here.' },
  { text: 'increase', meaning: '增加', example: 'We must increase our daily effort.' },
  { text: 'inform', meaning: '通知', example: 'Please inform me of any changes.' },
  { text: 'insist', meaning: '坚持', example: 'He did insist on paying for dinner.' },
  { text: 'invite', meaning: '邀请', example: 'We will invite all our friends to come.' },
  { text: 'join', meaning: '加入', example: 'Do you want to join our team today?' },
  { text: 'kick', meaning: '踢', example: 'The child kicked the ball very hard.' },
  { text: 'kill', meaning: '杀死', example: 'The cold can kill these small plants.' },
  { text: 'kiss', meaning: '亲吻', example: 'She gave the baby a soft kiss.' },
  { text: 'kneel', meaning: '跪', example: 'He had to kneel down to fix the shoe.' },
  { text: 'knock', meaning: '敲', example: 'Knock on the door before you enter.' },
  { text: 'lay', meaning: '放', example: 'Lay the book on the table, please.' },
  { text: 'lead', meaning: '领导', example: 'She was chosen to lead the group.' },
  { text: 'lift', meaning: '举起', example: 'Lift the heavy box with care.' },
  { text: 'link', meaning: '连接', example: 'There is a strong link between the two.' },
  { text: 'listen', meaning: '听', example: 'Listen carefully to what I say.' },
  { text: 'load', meaning: '装载', example: 'Load the bags onto the truck now.' },
  { text: 'manage', meaning: '设法', example: 'She can manage all the work by herself.' },
  { text: 'march', meaning: '行军', example: 'The army will march at dawn tomorrow.' },
  { text: 'mix', meaning: '混合', example: 'Mix the flour with some cold water.' },
  { text: 'murder', meaning: '谋杀', example: 'The police investigated the murder case.' },
  { text: 'nod', meaning: '点头', example: 'She did nod her head in agreement.' },
  { text: 'obey', meaning: '服从', example: 'Children must obey the safety rules.' },
  { text: 'obtain', meaning: '获得', example: 'You can obtain this book at the store.' },
  { text: 'occur', meaning: '发生', example: 'Accidents can occur without warning.' },
  { text: 'operate', meaning: '操作', example: 'Can you operate this machine for me?' },
  { text: 'oppose', meaning: '反对', example: 'They did oppose the new law strongly.' },
  { text: 'owe', meaning: '欠', example: 'I do owe you a great deal of money.' },
  { text: 'pass', meaning: '经过', example: 'We will pass through the old town.' },
  { text: 'perform', meaning: '表演', example: 'She will perform on the stage tonight.' },
  { text: 'permit', meaning: '允许', example: 'They will not permit smoking inside.' },
  { text: 'persuade', meaning: '说服', example: 'Try to persuade him to come with us.' },
  { text: 'pick', meaning: '挑选', example: 'Pick the best one from all the items.' },
  { text: 'plan', meaning: '计划', example: 'We need a good plan for the project.' },
  { text: 'plant', meaning: '种植', example: 'We will plant new trees in the spring.' },
  { text: 'pour', meaning: '倒', example: 'Pour some milk into the big cup.' },
  { text: 'pray', meaning: '祈祷', example: 'We all pray for peace in the world.' },
  { text: 'prefer', meaning: '偏好', example: 'I prefer tea to coffee in the morning.' },
  { text: 'prepare', meaning: '准备', example: 'Prepare the room for the meeting.' },
  { text: 'produce', meaning: '生产', example: 'They produce good work at this factory.' },
  { text: 'protect', meaning: '保护', example: 'We must protect the small children.' },
  { text: 'prove', meaning: '证明', example: 'Can you prove this is true for us?' },
  { text: 'provide', meaning: '提供', example: 'They will provide food for everyone.' },
  { text: 'publish', meaning: '出版', example: 'They will publish the new book soon.' },
  { text: 'pull', meaning: '拉', example: 'Pull the door hard to open it now.' },
  { text: 'pump', meaning: '泵', example: 'Use the pump to get water from the well.' },
  { text: 'push', meaning: '推', example: 'Push the door to open it from the inside.' },
  { text: 'raise', meaning: '举起', example: 'Raise your hand if you know the answer.' },
  { text: 'reach', meaning: '到达', example: 'We will reach the city by evening time.' },
  { text: 'receive', meaning: '收到', example: 'I did receive your letter yesterday.' },
  { text: 'reduce', meaning: '减少', example: 'We must reduce the cost of this project.' },
  { text: 'reflect', meaning: '反射', example: 'The mirror will reflect your face clearly.' },
  { text: 'refuse', meaning: '拒绝', example: 'He did refuse to answer the question.' },
  { text: 'remain', meaning: '保持', example: 'Please remain calm in this situation.' },
  { text: 'remove', meaning: '移除', example: 'Remove the old cover from the table.' },
  { text: 'replace', meaning: '替换', example: 'We need to replace the broken window.' },
  { text: 'require', meaning: '需要', example: 'This job will require much hard work.' },
  { text: 'resist', meaning: '抵抗', example: 'She did resist the temptation to eat more.' },
  { text: 'respond', meaning: '回答', example: 'Please respond to my question now.' },
  { text: 'rise', meaning: '上升', example: 'The sun will rise early tomorrow morning.' },
  { text: 'roll', meaning: '滚动', example: 'The ball will roll down the big hill.' },
  { text: 'satisfy', meaning: '满足', example: 'This result will satisfy most of the people.' },
  { text: 'search', meaning: '搜索', example: 'They will search for the lost item all day.' },
  { text: 'select', meaning: '挑选', example: 'Select the best one from all the choices.' },
  { text: 'separate', meaning: '分开', example: 'Separate the good fruit from the bad.' },
  { text: 'serve', meaning: '服务', example: 'They serve good food at this restaurant.' },
  { text: 'settle', meaning: '定居', example: 'They want to settle in a quiet small town.' },
  { text: 'shake', meaning: '摇', example: 'Shake the bottle well before you drink.' },
  { text: 'shoot', meaning: '射击', example: 'The hunter will shoot at the target now.' },
  { text: 'sink', meaning: '下沉', example: 'Heavy things will sink in deep water.' },
  { text: 'sit', meaning: '坐', example: 'Come and sit down here with me now.' },
  { text: 'slide', meaning: '滑动', example: 'The book will slide off the edge of the table.' },
  { text: 'sort', meaning: '分类', example: 'Sort these things into two main piles.' },
  { text: 'speak', meaning: '说话', example: 'Speak clearly so everyone can hear you.' },
  { text: 'spread', meaning: '展开', example: 'Spread the map out on the table here.' },
  { text: 'stand', meaning: '站立', example: 'Please stand up and face the front now.' },
  { text: 'start', meaning: '开始', example: 'When does the meeting start today?' },
  { text: 'steal', meaning: '偷', example: 'It is wrong to steal from other people.' },
  { text: 'stick', meaning: '粘', example: 'Stick the paper onto the wall with glue.' },
  { text: 'stop', meaning: '停止', example: 'Stop talking and listen to the teacher.' },
  { text: 'stretch', meaning: '伸展', example: 'Stretch your arms out wide before exercise.' },
  { text: 'strike', meaning: '打击', example: 'The clock will strike twelve at noon.' },
  { text: 'study', meaning: '学习', example: 'Study hard and you will pass the test.' },
  { text: 'succeed', meaning: '成功', example: 'If you work hard you will succeed in life.' },
  { text: 'supply', meaning: '供应', example: 'They will supply food for the big event.' },
  { text: 'support', meaning: '支持', example: 'We will support you in this difficult time.' },
  { text: 'suppose', meaning: '假设', example: 'I suppose you are right about this matter.' },
  { text: 'surprise', meaning: '惊喜', example: 'The party was a big surprise for her.' },
  { text: 'surround', meaning: '包围', example: 'Mountains surround the small quiet village.' },
  { text: 'survive', meaning: '生存', example: 'Only a few plants can survive the cold.' },
  { text: 'suspect', meaning: '怀疑', example: 'I suspect he knows the real answer.' },
  { text: 'swallow', meaning: '吞', example: 'Swallow the medicine with some water.' },
  { text: 'sweep', meaning: '打扫', example: 'Sweep the floor before the guests arrive.' },
  { text: 'swim', meaning: '游泳', example: 'The children love to swim in the lake.' },
  { text: 'swing', meaning: '摇摆', example: 'The sign will swing in the strong wind.' },
  { text: 'teach', meaning: '教', example: 'She did teach us many good things.' },
  { text: 'tear', meaning: '撕', example: 'Be careful not to tear the paper there.' },
  { text: 'throw', meaning: '扔', example: 'Throw the ball to me when I am ready.' },
  { text: 'tidy', meaning: '整理', example: 'Tidy up your room before you go out.' },
  { text: 'tip', meaning: '尖端', example: 'Be careful at the tip of the sharp knife.' },
  { text: 'toss', meaning: '抛', example: 'Toss the coin and see which side comes up.' },
  { text: 'touch', meaning: '触摸', example: 'Do not touch the hot surface with bare hands.' },
  { text: 'trace', meaning: '追踪', example: 'Try to trace the source of the problem.' },
  { text: 'translate', meaning: '翻译', example: 'Can you translate this into Chinese for me?' },
  { text: 'travel', meaning: '旅行', example: 'We will travel across the country by car.' },
  { text: 'treat', meaning: '对待', example: 'Treat other people the way you want.' },
  { text: 'trick', meaning: '诡计', example: 'That was just a trick to make us laugh.' },
  { text: 'try', meaning: '尝试', example: 'Try your best to finish the work on time.' },
  { text: 'twist', meaning: '扭', example: 'Twist the lid hard to open the jar.' },
  { text: 'unite', meaning: '联合', example: 'The two groups will unite for the cause.' },
  { text: 'urge', meaning: '催促', example: 'We urge you to make a decision now.' },
  { text: 'use', meaning: '使用', example: 'Use your own judgment in this matter.' },
  { text: 'visit', meaning: '访问', example: 'We will visit our friends this weekend.' },
  { text: 'wait', meaning: '等待', example: 'Please wait here until I come back.' },
  { text: 'warn', meaning: '警告', example: 'I must warn you about the dangers here.' },
  { text: 'wash', meaning: '洗', example: 'Wash your hands before you eat the food.' },
  { text: 'wave', meaning: '挥手', example: 'She will wave goodbye to her friend now.' },
  { text: 'wear', meaning: '穿', example: 'Wear warm clothes in the cold weather.' },
  { text: 'weigh', meaning: '称重', example: 'Weigh the fruit before you buy it here.' },
  { text: 'win', meaning: '赢', example: 'She will win the game if she plays well.' },

]
