/**
 * Built-in CEFR-graded vocabulary the user can adopt with one click,
 * avoiding a model-generation round-trip. Each entry has an English word and
 * a short Chinese meaning plus a tiny example.
 */

export interface BuiltinWord {
  text: string
  meaning: string
  example: string
  exampleMeaning: string
}

export interface BuiltinList {
  id: string
  label: string
  level: string
  words: BuiltinWord[]
}

export const BUILTIN_LISTS: BuiltinList[] = [
  {
    id: 'cefr-a1', label: 'A1 基础', level: 'A1',
    words: [
      { text: 'apple', meaning: '苹果', example: 'I eat an apple every morning.', exampleMeaning: '我每天早上吃苹果' },
      { text: 'book', meaning: '书', example: 'She is reading a book.', exampleMeaning: '她在读一本书' },
      { text: 'water', meaning: '水', example: 'Can I have some water?', exampleMeaning: '能给我些水吗' },
      { text: 'friend', meaning: '朋友', example: 'He is my best friend.', exampleMeaning: '他是我最好的朋友' },
      { text: 'happy', meaning: '高兴的', example: 'I am so happy today.', exampleMeaning: '我今天很高兴' },
      { text: 'morning', meaning: '早晨', example: 'Good morning, everyone.', exampleMeaning: '大家早上好' },
      { text: 'house', meaning: '房子', example: 'They live in a big house.', exampleMeaning: '他们住在大房子里' },
      { text: 'teacher', meaning: '老师', example: 'Our teacher is very kind.', exampleMeaning: '我们老师很善良' },
      { text: 'run', meaning: '跑', example: 'I run in the park every day.', exampleMeaning: '我每天在公园跑步' },
      { text: 'blue', meaning: '蓝色的', example: 'The sky is blue.', exampleMeaning: '天空是蓝色的' },
      { text: 'school', meaning: '学校', example: 'The children go to school.', exampleMeaning: '孩子们去上学' },
      { text: 'cat', meaning: '猫', example: 'The cat is sleeping.', exampleMeaning: '猫在睡觉' },
      { text: 'family', meaning: '家庭', example: 'My family is very big.', exampleMeaning: '我的家庭很大' },
      { text: 'food', meaning: '食物', example: 'The food here is delicious.', exampleMeaning: '这里的食物很好吃' },
      { text: 'help', meaning: '帮助', example: 'Can you help me?', exampleMeaning: '你能帮帮我吗' },
      { text: 'music', meaning: '音乐', example: 'I like listening to music.', exampleMeaning: '我喜欢听音乐' },
      { text: 'work', meaning: '工作', example: 'He goes to work by bus.', exampleMeaning: '他坐公交车上班' },
      { text: 'time', meaning: '时间', example: 'What time is it now?', exampleMeaning: '现在几点了' },
      { text: 'car', meaning: '汽车', example: 'She drives a red car.', exampleMeaning: '她开一辆红色汽车' },
      { text: 'dog', meaning: '狗', example: 'The dog is very cute.', exampleMeaning: '这只狗很可爱' },
      { text: 'brother', meaning: '兄弟', example: 'My brother is older than me.', exampleMeaning: '我哥哥比我大' },
      { text: 'door', meaning: '门', example: 'Please close the door.', exampleMeaning: '请关上门' },
      { text: 'sun', meaning: '太阳', example: 'The sun is very hot today.', exampleMeaning: '今天太阳很热' },
      { text: 'pen', meaning: '笔', example: 'Can I borrow your pen?', exampleMeaning: '能借你的笔吗' },
      { text: 'eat', meaning: '吃', example: 'We eat dinner at six.', exampleMeaning: '我们六点吃晚饭' },
      { text: 'drink', meaning: '喝', example: 'I drink tea every morning.', exampleMeaning: '我每天早上喝茶' },
      { text: 'sleep', meaning: '睡觉', example: 'I sleep eight hours a night.', exampleMeaning: '我每晚睡八小时' },
      { text: 'big', meaning: '大的', example: 'This is a big city.', exampleMeaning: '这是一座大城市' },
      { text: 'small', meaning: '小的', example: 'I have a small cat.', exampleMeaning: '我有一只小猫' },
      { text: 'new', meaning: '新的', example: 'I bought a new phone.', exampleMeaning: '我买了一部新手机' },
    ],
  },
  {
    id: 'cefr-a2', label: 'A2 初级', level: 'A2',
    words: [
      { text: 'expensive', meaning: '昂贵的', example: 'This phone is too expensive.', exampleMeaning: '这部手机太贵了' },
      { text: 'journey', meaning: '旅程', example: 'We enjoyed the long journey.', exampleMeaning: '我们享受了漫长的旅程' },
      { text: 'decide', meaning: '决定', example: 'It is hard to decide.', exampleMeaning: '很难做出决定' },
      { text: 'neighbor', meaning: '邻居', example: 'My neighbor is very friendly.', exampleMeaning: '我的邻居很友好' },
      { text: 'believe', meaning: '相信', example: 'I believe you.', exampleMeaning: '我相信你' },
      { text: 'borrow', meaning: '借', example: 'May I borrow your pen?', exampleMeaning: '能借你的笔吗' },
      { text: 'courage', meaning: '勇气', example: 'It takes courage to try.', exampleMeaning: '尝试需要勇气' },
      { text: 'promise', meaning: '承诺', example: 'I promise to help you.', exampleMeaning: '我答应帮助你' },
      { text: 'weather', meaning: '天气', example: 'The weather is nice today.', exampleMeaning: '今天天气很好' },
      { text: 'arrive', meaning: '到达', example: 'We arrived at the airport early.', exampleMeaning: '我们早早到了机场' },
      { text: 'begin', meaning: '开始', example: 'The class begins at nine.', exampleMeaning: '课程九点开始' },
      { text: 'bring', meaning: '带来', example: 'Please bring your book tomorrow.', exampleMeaning: '请明天带上你的书' },
      { text: 'change', meaning: '改变', example: 'I want to change my clothes.', exampleMeaning: '我想换衣服' },
      { text: 'choose', meaning: '选择', example: 'You can choose any color.', exampleMeaning: '你可以选任何颜色' },
      { text: 'enjoy', meaning: '享受', example: 'We enjoy playing football.', exampleMeaning: '我们喜欢踢足球' },
      { text: 'expect', meaning: '期望', example: 'I expect to see you soon.', exampleMeaning: '我期待很快见到你' },
      { text: 'follow', meaning: '跟随', example: 'Please follow me this way.', exampleMeaning: '请跟我走这边' },
      { text: 'happen', meaning: '发生', example: 'What happened yesterday?', exampleMeaning: '昨天发生了什么' },
      { text: 'invite', meaning: '邀请', example: 'I will invite my friends.', exampleMeaning: '我会邀请我的朋友' },
      { text: 'laugh', meaning: '笑', example: 'The joke made us laugh.', exampleMeaning: '笑话让我们笑了' },
      { text: 'leave', meaning: '离开', example: 'We leave at eight o\'clock.', exampleMeaning: '我们八点出发' },
      { text: 'message', meaning: '信息', example: 'I left you a message.', exampleMeaning: '我给你留了言' },
      { text: 'notice', meaning: '注意到', example: 'Did you notice the sign?', exampleMeaning: '你注意到那个标志了吗' },
      { text: 'offer', meaning: '提供', example: 'She offered me a cup of tea.', exampleMeaning: '她给我倒了杯茶' },
      { text: 'prefer', meaning: '更喜欢', example: 'I prefer coffee to tea.', exampleMeaning: '比起茶我更喜欢咖啡' },
      { text: 'receive', meaning: '收到', example: 'I received your letter.', exampleMeaning: '我收到了你的信' },
      { text: 'remember', meaning: '记得', example: 'Do you remember my name?', exampleMeaning: '你还记得我的名字吗' },
      { text: 'suggest', meaning: '建议', example: 'Can you suggest a good restaurant?', exampleMeaning: '能推荐一家好餐厅吗' },
      { text: 'travel', meaning: '旅行', example: 'I like to travel around the world.', exampleMeaning: '我喜欢环游世界' },
      { text: 'understand', meaning: '理解', example: 'I understand the problem now.', exampleMeaning: '我现在理解这个问题了' },
    ],
  },
  {
    id: 'cefr-b1', label: 'B1 中级', level: 'B1',
    words: [
      { text: 'achieve', meaning: '实现', example: 'She worked hard to achieve her goal.', exampleMeaning: '她努力实现了目标' },
      { text: 'opportunity', meaning: '机会', example: 'This is a great opportunity.', exampleMeaning: '这是一个好机会' },
      { text: 'improve', meaning: '提高', example: 'I want to improve my English.', exampleMeaning: '我想提高英语水平' },
      { text: 'confident', meaning: '自信的', example: 'He feels confident about the exam.', exampleMeaning: '他对考试充满信心' },
      { text: 'environment', meaning: '环境', example: 'We must protect the environment.', exampleMeaning: '我们必须保护环境' },
      { text: 'appreciate', meaning: '感激', example: 'I appreciate your help.', exampleMeaning: '感谢你的帮助' },
      { text: 'responsible', meaning: '负责的', example: 'You are responsible for this task.', exampleMeaning: '你负责这项任务' },
      { text: 'experience', meaning: '经验', example: 'She has a lot of experience.', exampleMeaning: '她经验丰富' },
      { text: 'available', meaning: '可用的', example: 'Is this seat available?', exampleMeaning: '这个座位有人吗' },
      { text: 'compare', meaning: '比较', example: 'Let us compare the two options.', exampleMeaning: '让我们比较两个选项' },
      { text: 'concern', meaning: '担心', example: 'I am concerned about his health.', exampleMeaning: '我担心他的健康' },
      { text: 'continue', meaning: '继续', example: 'Please continue with your story.', exampleMeaning: '请继续讲你的故事' },
      { text: 'develop', meaning: '发展', example: 'We need to develop new skills.', exampleMeaning: '我们需要培养新技能' },
      { text: 'encourage', meaning: '鼓励', example: 'My teacher encouraged me to study.', exampleMeaning: '老师鼓励我学习' },
      { text: 'essential', meaning: '必要的', example: 'Sleep is essential for health.', exampleMeaning: '睡眠对健康至关重要' },
      { text: 'gradually', meaning: '逐渐地', example: 'The weather is gradually warming.', exampleMeaning: '天气逐渐变暖了' },
      { text: 'influence', meaning: '影响', example: 'Parents influence their children.', exampleMeaning: '父母影响着孩子' },
      { text: 'maintain', meaning: '维持', example: 'We must maintain our friendships.', exampleMeaning: '我们必须维护友谊' },
      { text: 'negotiate', meaning: '谈判', example: 'They negotiated a new deal.', exampleMeaning: '他们谈成了新交易' },
      { text: 'obvious', meaning: '明显的', example: 'The answer is quite obvious.', exampleMeaning: '答案很明显' },
      { text: 'participate', meaning: '参加', example: 'Everyone should participate in the meeting.', exampleMeaning: '每个人都应参加会议' },
      { text: 'recommend', meaning: '推荐', example: 'I recommend this book to you.', exampleMeaning: '我向你推荐这本书' },
      { text: 'regular', meaning: '定期的', example: 'I go to the gym on a regular basis.', exampleMeaning: '我经常去健身房' },
      { text: 'significant', meaning: '重要的', example: 'This is a significant achievement.', exampleMeaning: '这是重要的成就' },
      { text: 'strategy', meaning: '策略', example: 'We need a better strategy.', exampleMeaning: '我们需要更好的策略' },
      { text: 'succeed', meaning: '成功', example: 'If you work hard, you will succeed.', exampleMeaning: '努力就会成功' },
      { text: 'support', meaning: '支持', example: 'Thank you for your support.', exampleMeaning: '谢谢你的支持' },
      { text: 'traditional', meaning: '传统的', example: 'We celebrated a traditional holiday.', exampleMeaning: '我们庆祝了传统节日' },
      { text: 'valuable', meaning: '有价值的', example: 'This painting is very valuable.', exampleMeaning: '这幅画很有价值' },
      { text: 'withdraw', meaning: '撤回', example: 'She decided to withdraw from the race.', exampleMeaning: '她决定退出比赛' },
    ],
  },
  {
    id: 'cefr-b2', label: 'B2 中高级', level: 'B2',
    words: [
      { text: 'alternative', meaning: '替代方案', example: 'We need an alternative plan.', exampleMeaning: '我们需要备选方案' },
      { text: 'controversial', meaning: '有争议的', example: 'The topic is quite controversial.', exampleMeaning: '这个话题很有争议' },
      { text: 'inevitable', meaning: '不可避免的', example: 'Change is inevitable.', exampleMeaning: '变化是不可避免的' },
      { text: 'perspective', meaning: '视角', example: 'Look at it from a new perspective.', exampleMeaning: '换个新角度看' },
      { text: 'thorough', meaning: '彻底的', example: 'We did a thorough review.', exampleMeaning: '我们做了彻底的审查' },
      { text: 'vulnerable', meaning: '脆弱的', example: 'The system is vulnerable to attacks.', exampleMeaning: '系统容易受到攻击' },
      { text: 'compromise', meaning: '妥协', example: 'We reached a reasonable compromise.', exampleMeaning: '我们达成了合理妥协' },
      { text: 'acknowledge', meaning: '承认', example: 'He acknowledged his mistake.', exampleMeaning: '他承认了自己的错误' },
      { text: 'ambiguous', meaning: '模棱两可的', example: 'His answer was ambiguous.', exampleMeaning: '他的回答模棱两可' },
      { text: 'bias', meaning: '偏见', example: 'We should avoid bias in research.', exampleMeaning: '研究中应避免偏见' },
      { text: 'comprehensive', meaning: '全面的', example: 'We need a comprehensive analysis.', exampleMeaning: '我们需要全面分析' },
      { text: 'consequence', meaning: '后果', example: 'What are the consequences of this?', exampleMeaning: '这会有什么后果' },
      { text: 'convince', meaning: '说服', example: 'She convinced me to stay.', exampleMeaning: '她说服了我留下' },
      { text: 'demonstrate', meaning: '证明', example: 'The experiment demonstrated the theory.', exampleMeaning: '实验证明了该理论' },
      { text: 'elaborate', meaning: '详细的', example: 'Could you elaborate on your idea?', exampleMeaning: '能详细说说你的想法吗' },
      { text: 'emphasize', meaning: '强调', example: 'I want to emphasize this point.', exampleMeaning: '我想强调这一点' },
      { text: 'fluctuate', meaning: '波动', example: 'Prices tend to fluctuate.', exampleMeaning: '价格往往会波动' },
      { text: 'fundamental', meaning: '根本的', example: 'This is a fundamental problem.', exampleMeaning: '这是一个根本问题' },
      { text: 'hesitate', meaning: '犹豫', example: 'Do not hesitate to ask for help.', exampleMeaning: '有问题尽管问' },
      { text: 'illustrate', meaning: '说明', example: 'This chart illustrates the trend.', exampleMeaning: '这张图说明了趋势' },
      { text: 'justify', meaning: '证明合理', example: 'How do you justify this decision?', exampleMeaning: '你怎么证明这决定合理' },
      { text: 'negligible', meaning: '微不足道的', example: 'The difference is negligible.', exampleMeaning: '差别微乎其微' },
      { text: 'obstacle', meaning: '障碍', example: 'Lack of funding is a major obstacle.', exampleMeaning: '资金不足是主要障碍' },
      { text: 'paradox', meaning: '悖论', example: 'This situation is a real paradox.', exampleMeaning: '这真是个悖论' },
      { text: 'predominant', meaning: '主要的', example: 'English is the predominant language.', exampleMeaning: '英语是主要语言' },
      { text: 'reinforce', meaning: '加强', example: 'This evidence reinforces our theory.', exampleMeaning: '证据加强了我们的理论' },
      { text: 'simultaneously', meaning: '同时地', example: 'Both events happened simultaneously.', exampleMeaning: '两件事同时发生了' },
      { text: 'sufficient', meaning: '足够的', example: 'We have sufficient evidence.', exampleMeaning: '我们有充分的证据' },
      { text: 'tentative', meaning: '暂定的', example: 'We have a tentative agreement.', exampleMeaning: '我们达成了初步协议' },
      { text: 'undermine', meaning: '削弱', example: 'It could undermine public trust.', exampleMeaning: '这会削弱公众信任' },
    ],
  },
  {
    id: 'cefr-c1', label: 'C1 高级', level: 'C1',
    words: [
      { text: 'consequently', meaning: '因此', example: 'Consequently, we changed the plan.', exampleMeaning: '因此我们改变了计划' },
      { text: 'deteriorate', meaning: '恶化', example: 'The situation began to deteriorate.', exampleMeaning: '情况开始恶化了' },
      { text: 'implication', meaning: '影响', example: 'What are the implications of this?', exampleMeaning: '这有什么影响' },
      { text: 'proficient', meaning: '熟练的', example: 'She is proficient in three languages.', exampleMeaning: '她精通三种语言' },
      { text: 'substantial', meaning: '大量的', example: 'There was a substantial increase.', exampleMeaning: '有了大幅增长' },
      { text: 'advocate', meaning: '提倡', example: 'She advocates for equal rights.', exampleMeaning: '她倡导平等权利' },
      { text: 'alleviate', meaning: '缓解', example: 'The medicine helped alleviate the pain.', exampleMeaning: '药物缓解了疼痛' },
      { text: 'approximate', meaning: '大约的', example: 'The approximate cost is five hundred dollars.', exampleMeaning: '大约花费五百美元' },
      { text: 'coherent', meaning: '连贯的', example: 'She presented a coherent argument.', exampleMeaning: '她提出了连贯的论点' },
      { text: 'compile', meaning: '汇编', example: 'We compiled a list of references.', exampleMeaning: '我们汇编了参考文献' },
      { text: 'conceivable', meaning: '可想象的', example: 'Every conceivable option was explored.', exampleMeaning: '探索了所有能想到的选项' },
      { text: 'consensus', meaning: '共识', example: 'We finally reached a consensus.', exampleMeaning: '我们终于达成了共识' },
      { text: 'constraint', meaning: '限制', example: 'Budget constraints limited our options.', exampleMeaning: '预算限制了我们的选择' },
      { text: 'contemplate', meaning: '沉思', example: 'She sat and contemplated her future.', exampleMeaning: '她坐着思考未来' },
      { text: 'contradict', meaning: '反驳', example: 'The evidence contradicts his claim.', exampleMeaning: '证据反驳了他的说法' },
      { text: 'controversy', meaning: '争议', example: 'The decision caused a lot of controversy.', exampleMeaning: '这个决定引起很大争议' },
      { text: 'correspond', meaning: '对应', example: 'The results correspond with our predictions.', exampleMeaning: '结果与预测一致' },
      { text: 'diminish', meaning: '减少', example: 'His influence began to diminish.', exampleMeaning: '他的影响力开始减弱' },
      { text: 'distinguish', meaning: '区分', example: 'It is hard to distinguish the two.', exampleMeaning: '很难区分这两者' },
      { text: 'elicit', meaning: '引出', example: 'The question elicited a strong response.', exampleMeaning: '问题引发了强烈反响' },
      { text: 'empirical', meaning: '经验的', example: 'We need empirical evidence to support this.', exampleMeaning: '需要实证来支持' },
      { text: 'explicit', meaning: '明确的', example: 'The instructions were very explicit.', exampleMeaning: '说明非常明确' },
      { text: 'facilitate', meaning: '促进', example: 'Technology can facilitate learning.', exampleMeaning: '科技能促进学习' },
      { text: 'fragment', meaning: '片段', example: 'We only found a fragment of the text.', exampleMeaning: '我们只找到部分文本' },
      { text: 'hypothesis', meaning: '假设', example: 'The hypothesis was tested repeatedly.', exampleMeaning: '假设被反复验证' },
      { text: 'ideology', meaning: '意识形态', example: 'Political ideology shapes policies.', exampleMeaning: '政治意识形态影响政策' },
      { text: 'increment', meaning: '增量', example: 'Each increment brings us closer to the goal.', exampleMeaning: '每次增量让我们更近一步' },
      { text: 'inherent', meaning: '固有的', example: 'There are inherent risks in the plan.', exampleMeaning: '计划中存在固有风险' },
      { text: 'meticulous', meaning: '一丝不苟的', example: 'She is meticulous about details.', exampleMeaning: '她对细节一丝不苟' },
      { text: 'prerequisite', meaning: '先决条件', example: 'Experience is a prerequisite for this job.', exampleMeaning: '经验是这份工作的前提' },
    ],
  },
  {
    id: 'cefr-c2', label: 'C2 精通', level: 'C2',
    words: [
      { text: 'aberration', meaning: '反常', example: 'The result was a statistical aberration.', exampleMeaning: '结果是统计上的异常' },
      { text: 'circumspect', meaning: '谨慎的', example: 'Be circumspect in your reply.', exampleMeaning: '回复时要谨慎' },
      { text: 'ephemeral', meaning: '短暂的', example: 'Fame is often ephemeral.', exampleMeaning: '名声往往是短暂的' },
      { text: 'quintessential', meaning: '典型的', example: 'She is the quintessential leader.', exampleMeaning: '她是典型的领导者' },
      { text: 'ubiquitous', meaning: '无处不在的', example: 'Smartphones are ubiquitous now.', exampleMeaning: '智能手机现在无处不在' },
      { text: 'acquiesce', meaning: '默许', example: 'He reluctantly acquiesced to the demand.', exampleMeaning: '他勉强默许了要求' },
      { text: 'amalgamate', meaning: '合并', example: 'The two companies amalgamated last year.', exampleMeaning: '两家公司去年合并了' },
      { text: 'ameliorate', meaning: '改善', example: 'Steps were taken to ameliorate the situation.', exampleMeaning: '采取措施改善了情况' },
      { text: 'anomaly', meaning: '异常', example: 'The data showed a clear anomaly.', exampleMeaning: '数据显示了明显异常' },
      { text: 'auspicious', meaning: '吉利的', example: 'It was an auspicious start to the year.', exampleMeaning: '这是个吉利的开端' },
      { text: 'capitulate', meaning: '投降', example: 'The army was forced to capitulate.', exampleMeaning: '军队被迫投降了' },
      { text: 'catalyst', meaning: '催化剂', example: 'The event was a catalyst for change.', exampleMeaning: '该事件是变革的催化剂' },
      { text: 'clandestine', meaning: '秘密的', example: 'They held clandestine meetings.', exampleMeaning: '他们举行了秘密会议' },
      { text: 'conundrum', meaning: '难题', example: 'This ethical conundrum has no easy answer.', exampleMeaning: '这个伦理难题无简单答案' },
      { text: 'corroborate', meaning: '证实', example: 'The witness corroborated his story.', exampleMeaning: '证人证实了他的说法' },
      { text: 'dearth', meaning: '缺乏', example: 'There is a dearth of qualified candidates.', exampleMeaning: '缺乏合格的候选人' },
      { text: 'deleterious', meaning: '有害的', example: 'Pollution has deleterious effects on health.', exampleMeaning: '污染对健康有害' },
      { text: 'dichotomy', meaning: '二分法', example: 'There is a dichotomy between theory and practice.', exampleMeaning: '理论与实践存在二分' },
      { text: 'discern', meaning: '辨别', example: 'It was hard to discern the truth.', exampleMeaning: '很难辨别真相' },
      { text: 'discrepancy', meaning: '差异', example: 'There is a discrepancy in the reports.', exampleMeaning: '报告中存在差异' },
      { text: 'elucidate', meaning: '阐明', example: 'Could you elucidate this concept?', exampleMeaning: '能阐明这个概念吗' },
      { text: 'eminent', meaning: '杰出的', example: 'She is an eminent scientist.', exampleMeaning: '她是杰出的科学家' },
      { text: 'equivocal', meaning: '模棱两可的', example: 'His response was deliberately equivocal.', exampleMeaning: '他的回答故意模棱两可' },
      { text: 'exacerbate', meaning: '加剧', example: 'The policy only exacerbated the problem.', exampleMeaning: '政策只是加剧了问题' },
      { text: 'extraneous', meaning: '无关的', example: 'Remove all extraneous details from the report.', exampleMeaning: '删除报告中所有无关细节' },
      { text: 'fortuitous', meaning: '偶然的', example: 'A fortuitous encounter changed his life.', exampleMeaning: '一次偶然相遇改变了人生' },
      { text: 'gregarious', meaning: '爱社交的', example: 'She has a gregarious personality.', exampleMeaning: '她性格爱社交' },
      { text: 'impeccable', meaning: '无可挑剔的', example: 'Her taste in art is impeccable.', exampleMeaning: '她的艺术品味无可挑剔' },
      { text: 'juxtapose', meaning: '并列对比', example: 'The author juxtaposed wealth and poverty.', exampleMeaning: '作者将贫富并列对比' },
      { text: 'magnanimous', meaning: '宽宏大量的', example: 'She was magnanimous in victory.', exampleMeaning: '她在胜利时宽宏大量' },
    ],
  },
]

/** Look up a built-in list by its id. */
export function findBuiltinList(id: string): BuiltinList | undefined {
  return BUILTIN_LISTS.find(list => list.id === id)
}
